import { Router, type IRouter } from "express";
import achievementRouter from "./achievements.js";
import articleRouter from "./articles.js";
import authRouter from "./auth.js";
import communityRouter from "./communities.js";
import broadcastChannelRouter from "./broadcast-channels.js";
import diagnosticsRouter from "./diagnostics.js";
import docsRouter from "./docs.js";
import eventRouter from "./events.js";
import healthRouter from "./health.js";
import messageRouter from "./messages.js";
import notificationRouter from "./notifications.js";
import noteRouter from "./notes.js";
import postRouter from "./posts.js";
import productRouter from "./products.js";
import searchRouter from "./search.js";
import storyRouter from "./stories.js";
import streamRouter from "./streams.js";
import userRouter from "./users.js";
import videoRouter from "./videos.js";
import { economyRoutes } from "./economy-routes.js";
import { subscriptionRoutes } from "./subscriptions.js";
import mediaRouter from "./media.js";
import { aiRoutes } from "./ai.js";
import { businessRoutes } from "./business.js";
import { inviteRoutes } from "./invites.js";
import { onboardingRoutes } from "./onboarding.js";
import { projectRoutes } from "./projects.js";
import { reportRoutes } from "./reports.js";
import { creatorWorkspaceRoutes } from "./creator-workspace.js";
import profileInteractionRouter from "./profile-interactions.js";
import metricsRouter from "./metrics.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(diagnosticsRouter);
router.use(metricsRouter);
router.use(docsRouter);
router.use(authRouter);
router.use(mediaRouter);
router.use(userRouter);
router.use(profileInteractionRouter);
router.use(postRouter);
router.use(messageRouter);
router.use(notificationRouter);
router.use(noteRouter);
router.use(communityRouter);
router.use(broadcastChannelRouter);
router.use(searchRouter);
router.use(eventRouter);
router.use(productRouter);
router.use(articleRouter);
router.use(videoRouter);
router.use(storyRouter);
router.use(streamRouter);
router.use(achievementRouter);
router.use("/reports", reportRoutes);
router.use("/creator", creatorWorkspaceRoutes);
router.use("/business", businessRoutes);
router.use("/ai", aiRoutes);
router.use("/invites", inviteRoutes);
router.use("/onboarding", onboardingRoutes);
router.use("/projects", projectRoutes);
router.use("/economy", economyRoutes);
router.use("/subscriptions", subscriptionRoutes);

export default router;
