import { Router } from "express";
import { UserController } from "../controllers/user-controller.js";
import { authenticate } from "../middlewares/auth.js";
import { imageUpload } from "../middlewares/upload.js";
import { validateBody, validateParams, validateQuery } from "../middlewares/validation.js";
import { NotificationRepository } from "../repositories/notification-repository.js";
import { RedisRepository } from "../repositories/redis-repository.js";
import { UserRepository } from "../repositories/user-repository.js";
import { AuthService } from "../services/auth-service.js";
import { QueueService } from "../services/queue-service.js";
import { UserService } from "../services/user-service.js";
import { contactShieldSchema, deleteAccountSchema, privacySchema, searchUsersSchema, settingsSchema, updateProfileSchema } from "../validators/user.js";
import { followRequestIdParamSchema, userIdParamSchema, usernameParamSchema } from "../validators/params.js";
import { AccountService } from "../services/account-service.js";
import { AuthController } from "../controllers/auth-controller.js";
import { acceptTermsSchema } from "../validators/auth.js";
import { mediaRateLimiter } from "../middlewares/rate-limit.js";

const router = Router();
const userRepository = new UserRepository();
const redisRepository = new RedisRepository();
const userService = new UserService(userRepository, new NotificationRepository(), new QueueService());
const authService = new AuthService(userRepository, redisRepository);
const authController = new AuthController(authService);
const userController = new UserController(userService, authService, new AccountService(userRepository, redisRepository));

router.get("/users/search", authenticate, validateQuery(searchUsersSchema), userController.searchUsers);
router.get("/users/me", authenticate, userController.getCurrentUser);
router.post("/users/me/consent", authenticate, validateBody(acceptTermsSchema), authController.acceptTerms);
router.get("/users/me/export", authenticate, userController.exportAccount);
router.delete("/users/me", authenticate, validateBody(deleteAccountSchema), userController.deleteAccount);
router.get("/users/by-username/:username", authenticate, validateParams(usernameParamSchema), userController.getProfileByUsername);
router.get("/users/:userId", authenticate, validateParams(userIdParamSchema), userController.getProfile);
router.put("/users/me", authenticate, validateBody(updateProfileSchema), userController.updateProfile);
router.post("/users/me/avatar", authenticate, mediaRateLimiter, imageUpload.single("avatar"), userController.uploadAvatar);
router.post("/users/:userId/follow", authenticate, validateParams(userIdParamSchema), userController.followUser);
router.post("/users/:userId/unfollow", authenticate, validateParams(userIdParamSchema), userController.unfollowUser);
router.get("/users/:userId/followers", authenticate, validateParams(userIdParamSchema), userController.followers);
router.get("/users/:userId/following", authenticate, validateParams(userIdParamSchema), userController.following);
router.get("/users/me/favorites/creators", authenticate, userController.listFavoriteCreators);
router.get("/users/me/close-friends", authenticate, userController.listCloseFriends);
router.post("/users/:userId/close-friend", authenticate, validateParams(userIdParamSchema), userController.addCloseFriend);
router.delete("/users/:userId/close-friend", authenticate, validateParams(userIdParamSchema), userController.removeCloseFriend);
router.post("/users/:userId/favorite", authenticate, validateParams(userIdParamSchema), userController.favoriteCreator);
router.delete("/users/:userId/favorite", authenticate, validateParams(userIdParamSchema), userController.unfavoriteCreator);
router.get("/users/me/follow-requests", authenticate, userController.listFollowRequests);
router.post("/users/me/follow-requests/:requestId/accept", authenticate, validateParams(followRequestIdParamSchema), userController.acceptFollowRequest);
router.post("/users/me/follow-requests/:requestId/reject", authenticate, validateParams(followRequestIdParamSchema), userController.rejectFollowRequest);
router.put("/users/me/settings", authenticate, validateBody(settingsSchema), userController.settings);
router.put("/users/me/privacy", authenticate, validateBody(privacySchema), userController.updatePrivacy);
router.post("/users/:userId/block", authenticate, validateParams(userIdParamSchema), userController.blockUser);
router.post("/users/:userId/unblock", authenticate, validateParams(userIdParamSchema), userController.unblockUser);
router.post("/users/:userId/mute", authenticate, validateParams(userIdParamSchema), userController.muteUser);
router.post("/users/:userId/unmute", authenticate, validateParams(userIdParamSchema), userController.unmuteUser);
router.get("/users/me/contact-shields", authenticate, userController.listContactShields);
router.post("/users/me/contact-shields", authenticate, validateBody(contactShieldSchema), userController.addContactShields);
router.delete("/users/me/contact-shields/:shieldId", authenticate, userController.removeContactShield);

export default router;
