import type { User, Post, Story, Community, EventItem, Product, Article, Video, LiveStream, Conversation, Message, Notification } from './store';

export const MOCK_USERS: Record<string, User> = {
  'user-roy': {
    id: 'user-roy',
    username: 'yorayriniwnl',
    displayName: 'Ayush Roy',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop',
    bio: 'Founder & Full-Stack Architect @ Yor Talks. Building ambient systems, spatial computing tools, and high-performance product surfaces. 🚀⚡',
    followers: 24420,
    following: 720,
    followingIds: ['user-anya', 'user-aditi', 'user-marcus', 'user-sophia', 'user-elena', 'user-kai', 'user-valkyrie', 'user-tariq', 'user-zara', 'user-kavita', 'user-orion'],
    verified: true,
  },
  'user-anya': {
    id: 'user-anya',
    username: 'anyaa_yaps',
    displayName: 'Anya',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2564&auto=format&fit=crop',
    bio: '3D World Builder & Unreal Engine 5.4 Enthusiast 🎮✨ Exploring procedural environments, volumetric lighting & shader graphs.',
    followers: 48890,
    following: 940,
    followingIds: ['user-roy', 'user-marcus', 'user-chloe'],
    verified: true,
  },
  'user-aditi': {
    id: 'user-aditi',
    username: 'aditi_cofounder',
    displayName: 'Aditi Singh',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?q=80&w=2564&auto=format&fit=crop',
    bio: 'Co-Founder @ Yor Talks & Yor Zenith 🌌 Multimodal AI, community ecosystems & modern aesthetics. Organizing Global Hackathon 2026!',
    followers: 39420,
    following: 780,
    followingIds: ['user-roy', 'user-anya', 'user-elena'],
    verified: true,
  },
  'user-marcus': {
    id: 'user-marcus',
    username: 'marcus_ai',
    displayName: 'Marcus Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2564&auto=format&fit=crop',
    bio: 'AI Researcher & Spatial Computing Lead 🤖 Neuromorphic architecture, world models & real-time perception.',
    followers: 78450,
    following: 1120,
    followingIds: ['user-roy', 'user-sophia', 'user-maya'],
    verified: true,
  },
  'user-elena': {
    id: 'user-elena',
    username: 'elena_audio',
    displayName: 'Elena Rostova',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=2564&auto=format&fit=crop',
    bio: 'Audio Architect & Sound Synthesist 🎧 Modular synth lover, generative ambient textures & binaural soundscapes.',
    followers: 54710,
    following: 1110,
    followingIds: ['user-roy', 'user-kai'],
    verified: true,
  },
  'user-sophia': {
    id: 'user-sophia',
    username: 'sophia_ui',
    displayName: 'Sophia Chen',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=2564&auto=format&fit=crop',
    bio: 'Design Systems Lead @ Multiverse Studio. Minimalist typography, micro-interactions & tactile interfaces. ☕📐',
    followers: 114400,
    following: 1080,
    followingIds: ['user-roy', 'user-aditi'],
    verified: true,
  },
  'user-kai': {
    id: 'user-kai',
    username: 'kai_thorne',
    displayName: 'Kai Thorne',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2564&auto=format&fit=crop',
    bio: 'Cybernetic Game Director 🎮 Building immersive VR/XR experiences with cutting-edge shaders and physics.',
    followers: 49310,
    following: 890,
    followingIds: ['user-roy', 'user-anya'],
    verified: true,
  },
  'user-maya': {
    id: 'user-maya',
    username: 'maya_lin',
    displayName: 'Maya Lin',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2564&auto=format&fit=crop',
    bio: 'Quantum Computing & Zero-Knowledge Cryptography enthusiast 🌌 Exploring lattice cryptography & post-quantum security.',
    followers: 42120,
    following: 740,
    verified: true,
  },
  'user-jaxson': {
    id: 'user-jaxson',
    username: 'jaxson_hardware',
    displayName: 'Jaxson Reed',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2564&auto=format&fit=crop',
    bio: 'Custom Hardware Artisan & Mech Keyboard Creator ⌨️ CNC milling, anodized aluminum cases & custom PCB layouts.',
    followers: 69210,
    following: 1160,
    verified: true,
  },
  'user-chloe': {
    id: 'user-chloe',
    username: 'chloe_visuals',
    displayName: 'Chloe Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=2564&auto=format&fit=crop',
    bio: 'Generative Art Director & Motion Designer 🎨 Transforming mathematical equations into living digital canvases.',
    followers: 124300,
    following: 1390,
    verified: true,
  },
  'user-zephyr': {
    id: 'user-zephyr',
    username: 'zephyr_voss',
    displayName: 'Zephyr Voss',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=2564&auto=format&fit=crop',
    bio: 'Indie Hacker & Solopreneur 🛠️ Bootstrapping developer tools, CLI utilities and micro-SaaS products. Rust & TypeScript.',
    followers: 57890,
    following: 920,
    verified: false,
  },
  'user-liam': {
    id: 'user-liam',
    username: 'liam_devops',
    displayName: 'Liam O’Connor',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2564&auto=format&fit=crop',
    bio: 'Distributed Systems & Cloud Architecture Engineer ☁️ Kubernetes clusters, eBPF telemetry & zero-latency edge networks.',
    followers: 49430,
    following: 840,
    verified: true,
  },
  'user-valkyrie': {
    id: 'user-valkyrie',
    username: 'valk_cyber',
    displayName: 'Valkyrie Ray',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=2564&auto=format&fit=crop',
    bio: 'Offensive Security Researcher & Reverse Engineer 🛡️ Binary exploitation, smart contract audits & hardware security.',
    followers: 88900,
    following: 890,
    verified: true,
  },
  'user-tariq': {
    id: 'user-tariq',
    username: 'tariq_biotech',
    displayName: 'Dr. Tariq Al-Mansoor',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=2564&auto=format&fit=crop',
    bio: 'Computational Biologist & Protein Folding Architect 🧬 Simulating molecular dynamics with neural tensor networks.',
    followers: 48210,
    following: 710,
    verified: true,
  },
  'user-zara': {
    id: 'user-zara',
    username: 'zara_optics',
    displayName: 'Zara Thorne',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=2564&auto=format&fit=crop',
    bio: 'Astrophotographer & Optical Engineer 🔭 Capturing deep-sky nebulae and designing precision telescope mirrors.',
    followers: 71600,
    following: 810,
    verified: true,
  },
  'user-dante': {
    id: 'user-dante',
    username: 'dante_cyber',
    displayName: 'Dante Rivera',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?q=80&w=2564&auto=format&fit=crop',
    bio: 'Cyberpunk Author & Narrative World Builder 📚 Exploring future megacities, transhumanism & synthetic memories.',
    followers: 51900,
    following: 930,
    verified: false,
  },
  'user-kavita': {
    id: 'user-kavita',
    username: 'kavita_neuro',
    displayName: 'Kavita Patel',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=2564&auto=format&fit=crop',
    bio: 'Neural Interface Engineer & BCI Researcher 🧠 Decoding motor cortex potentials with non-invasive micro-electrode arrays.',
    followers: 56400,
    following: 770,
    verified: true,
  },
  'user-orion': {
    id: 'user-orion',
    username: 'orion_robotics',
    displayName: 'Orion Sterling',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=2564&auto=format&fit=crop',
    bio: 'Bipedal Robotics & Actuator Control Specialist 🤖 Designing compliant tendon-driven robotic limbs with zero backlash.',
    followers: 85800,
    following: 980,
    verified: true,
  },
  'user-aravind': {
    id: 'user-aravind',
    username: 'aravind_val',
    displayName: 'Aravind Rao',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2564&auto=format&fit=crop',
    bio: 'VCT Radiant Duelist & Esports Captain 🏆 Aim coach, clutch compilation maker & tactical gaming hardware fanatic.',
    followers: 165400,
    following: 420,
    verified: true,
  },
  'user-renata': {
    id: 'user-renata',
    username: 'renata_beats',
    displayName: 'Renata Silva',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=2564&auto=format&fit=crop',
    bio: 'Bass Music Producer & Live Modular Performer 🎛️⚡ Neurofunk, Cyber-DNB & warehouse raves across Tokyo, Berlin & Goa.',
    followers: 94200,
    following: 610,
    verified: true,
  },
  'user-kenji': {
    id: 'user-kenji',
    username: 'kenji_art',
    displayName: 'Kenji Sato',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=2564&auto=format&fit=crop',
    bio: 'Cyber-Samurai Illustrator & Visual Novel Creator 🎨 Kyoto based. Transforming neon reflections and ink into dynamic anime frames.',
    followers: 182300,
    following: 890,
    verified: true,
  },
  'user-leila': {
    id: 'user-leila',
    username: 'leila_noir',
    displayName: 'Leila Noor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=2564&auto=format&fit=crop',
    bio: 'Augmented Apparel & Cyberpunk Haute Couture 👗 Holographic fabrics, LED woven corsets & digital fashion drops on the blockchain.',
    followers: 210500,
    following: 1140,
    verified: true,
  },
  'user-priya': {
    id: 'user-priya',
    username: 'priya_ragas',
    displayName: 'Priya Sundaram',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=2564&auto=format&fit=crop',
    bio: 'Acoustic Fusion Sitarist & Microtonal Explorer 🪕 Combining classical Hindustani ragas with analog tape delays and lo-fi beats.',
    followers: 78900,
    following: 540,
    verified: true,
  },
  'user-lucas': {
    id: 'user-lucas',
    username: 'lucas_fpv',
    displayName: 'Lucas Moreau',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=2564&auto=format&fit=crop',
    bio: 'Custom FPV Freestyle Drone Pilot & 8K Cinematographer 🛸 Chasing waterfalls in Iceland and high-speed drifts in Shibuya.',
    followers: 142000,
    following: 790,
    verified: true,
  },
  'user-vikram': {
    id: 'user-vikram',
    username: 'vikram_quantum',
    displayName: 'Dr. Vikram Mehta',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2564&auto=format&fit=crop',
    bio: 'Quantum Computing & Lattice Cryptography Architect ⚛️ Qiskit algorithms, superconducting qubits & topological error correction.',
    followers: 61400,
    following: 380,
    verified: true,
  },
  'user-nadia': {
    id: 'user-nadia',
    username: 'nadia_exo',
    displayName: 'Nadia Volkova',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2564&auto=format&fit=crop',
    bio: 'Powered Exoskeletons & Neural Prosthetics Engineer 🦾 Carbon-fiber titanium linkages for human augmentation.',
    followers: 89300,
    following: 510,
    verified: true,
  },
  'user-sakura': {
    id: 'user-sakura',
    username: 'sakura_vtube',
    displayName: 'Sakura Miyamoto',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=2564&auto=format&fit=crop',
    bio: 'Virtual Streamer & Live2D/3D Rigging Virtuoso 🌸 Live motion capture, shaders, and real-time facial expression blendshapes.',
    followers: 340000,
    following: 220,
    verified: true,
  },
  'user-mateo': {
    id: 'user-mateo',
    username: 'mateo_aero',
    displayName: 'Mateo Rossi',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=2564&auto=format&fit=crop',
    bio: 'Hypercar Aerodynamics & Computational Fluid Dynamics 🏎️💨 Ground effect venturis, active DRS wings & carbon chassis design.',
    followers: 128900,
    following: 460,
    verified: true,
  },
  'user-anika': {
    id: 'user-anika',
    username: 'anika_coffee',
    displayName: 'Anika Das',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2564&auto=format&fit=crop',
    bio: 'Specialty Coffee Roaster & Extraction Chemist ☕ Anaerobic natural fermentation, TDS profiling & hand-poured Chemex ritual.',
    followers: 47200,
    following: 690,
    verified: false,
  },
  'user-yuki': {
    id: 'user-yuki',
    username: 'yuki_arcade',
    displayName: 'Yuki Tanaka',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=2564&auto=format&fit=crop',
    bio: 'Fighting Game Champion & Custom Fightstick Modder 🕹️ Sanwa leverless controller builds, 1ms polling rate firmware & frame data analysis.',
    followers: 98100,
    following: 340,
    verified: true,
  },
  'user-clara': {
    id: 'user-clara',
    username: 'clara_microtonal',
    displayName: 'Clara Dupont',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=2564&auto=format&fit=crop',
    bio: 'Avant-Garde Microtonal Vocalist & Granular Synthesist 🎙️ 31-EDO scale explorations, vocal harmonizers & modular delay chains.',
    followers: 64500,
    following: 480,
    verified: true,
  },
  'user-thorin': {
    id: 'user-thorin',
    username: 'thorin_forge',
    displayName: 'Thorin Lindqvist',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?q=80&w=2564&auto=format&fit=crop',
    bio: 'Damascus Steel Bladesmith & Metallurgy Artisan ⚔️ 512-layer folded pattern welding, differential clay tempering & bog oak handles.',
    followers: 112000,
    following: 290,
    verified: true,
  },
  'user-zane': {
    id: 'user-zane',
    username: 'zane_noir',
    displayName: 'Zane Sterling',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=2564&auto=format&fit=crop',
    bio: 'Cyberpunk Street Photographer & Neon Noir Colorist 📸 35mm Leica M6 & anamorphic cinematic lens master. Capturing rain in Neo-Tokyo.',
    followers: 198400,
    following: 410,
    verified: true,
  },
  'user-valeria': {
    id: 'user-valeria',
    username: 'valeria_kicks',
    displayName: 'Valeria Gomez',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=2564&auto=format&fit=crop',
    bio: '3D Footwear Architect & Procedural Sneaker Designer 👟 Generative lattice midsoles, parametric TPU outsoles & digital streetwear.',
    followers: 245000,
    following: 680,
    verified: true,
  },
  'user-taro': {
    id: 'user-taro',
    username: 'taro_siphon',
    displayName: 'Taro Takahashi',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=2564&auto=format&fit=crop',
    bio: 'Master Siphon Barista & Roasting Alchemist ☕ Kyoto vacuum pot brewing, Gesha micro-lots & precision refractometer analysis.',
    followers: 86400,
    following: 320,
    verified: true,
  },
  'user-milo': {
    id: 'user-milo',
    username: 'milo_dev',
    displayName: 'Milo Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2564&auto=format&fit=crop',
    bio: 'Indie Roguelike Dev & Chiptune Musician 🎮👾 Building procedural dungeon crawlers with custom Game Boy sound chip synthesisers in C++.',
    followers: 73900,
    following: 540,
    verified: true,
  },
  'user-hina': {
    id: 'user-hina',
    username: 'hina_mecha',
    displayName: 'Hina Mori',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=2564&auto=format&fit=crop',
    bio: 'Mecha 3D Animator & Hard-Surface Rigging Lead 🤖 Gundam-inspired kinematics, hydraulic hose physics & Blender geometry node sorcery.',
    followers: 174200,
    following: 490,
    verified: true,
  },
  'user-gabriel': {
    id: 'user-gabriel',
    username: 'gabriel_abyss',
    displayName: 'Gabriel Thorne',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=2564&auto=format&fit=crop',
    bio: 'Deep-Sea Submersible Pilot & Oceanographer 🌊 Deep Mariana Trench dives, hydrothermal vent research & bioluminescent species discovery.',
    followers: 119800,
    following: 280,
    verified: true,
  },
  'user-selena': {
    id: 'user-selena',
    username: 'selena_darkwave',
    displayName: 'Selena Moon',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=2564&auto=format&fit=crop',
    bio: 'Darkwave Pop Vocalist & Tape Loop Magician 🎙️🖤 Vintage Roland Space Echo, cassette loops, ethereal reverb & analog choir textures.',
    followers: 154000,
    following: 610,
    verified: true,
  },
  'user-alexei': {
    id: 'user-alexei',
    username: 'alexei_chess',
    displayName: 'Alexei Romanov',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?q=80&w=2564&auto=format&fit=crop',
    bio: 'Chess Grandmaster & Neural AlphaZero Engine Trainer ♟️ 2740 FIDE rating, Sicilian Defense theory & reinforcement learning evaluation nets.',
    followers: 218000,
    following: 340,
    verified: true,
  },
  'user-fatima': {
    id: 'user-fatima',
    username: 'fatima_patterns',
    displayName: 'Fatima Al-Zahra',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=2564&auto=format&fit=crop',
    bio: 'Algorithmic Geometry & Generative Tessellations 📐 Translating centuries-old Islamic girih tiling into mathematical GLSL fragment shaders.',
    followers: 98400,
    following: 420,
    verified: true,
  },
  'user-dax': {
    id: 'user-dax',
    username: 'dax_rotary',
    displayName: 'Dax Shepardson',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=2564&auto=format&fit=crop',
    bio: 'JDM Rotary Engine Tuner & Time Attack Pilot 🏎️🔥 20B 3-rotor bridgeport turbo builds, standalone ECU mapping & Tsukuba lap records.',
    followers: 184500,
    following: 390,
    verified: true,
  },
  'user-charlotte': {
    id: 'user-charlotte',
    username: 'charlotte_scent',
    displayName: 'Charlotte Dubois',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?q=80&w=2564&auto=format&fit=crop',
    bio: 'Haute Parfumerie & Olfactory Molecular Architect 🌸 Grasse based. Synthesizing petrichor, ancient resins, and ozone notes into bespoke scents.',
    followers: 132000,
    following: 580,
    verified: true,
  },
  'user-brennan': {
    id: 'user-brennan',
    username: 'brennan_vinyl',
    displayName: 'Brennan Brooks',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=2564&auto=format&fit=crop',
    bio: 'Direct-Drive Vinyl Lathe Mastering Engineer 🎙️💿 Neumann VMS-70 cutter head, lacquer discs & pure analog signal chain.',
    followers: 67100,
    following: 290,
    verified: true,
  },
  'user-ayesha': {
    id: 'user-ayesha',
    username: 'ayesha_grade',
    displayName: 'Ayesha Khan',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=2564&auto=format&fit=crop',
    bio: 'Senior Feature Film Colorist & 65mm IMAX Restorer 🎬 DaVinci Resolve Studio, ACES color management & custom photochemical film emulation.',
    followers: 149000,
    following: 510,
    verified: true,
  },
  'user-soren': {
    id: 'user-soren',
    username: 'soren_wood',
    displayName: 'Soren Kjaer',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=2564&auto=format&fit=crop',
    bio: 'Danish Minimalist Furniture Maker & Master Joiner 🪑 Hand-planed white oak, mortise and tenon joinery & organic oil finishes.',
    followers: 104500,
    following: 340,
    verified: true,
  },
  'user-kofi': {
    id: 'user-kofi',
    username: 'kofi_groove',
    displayName: 'Kofi Mensah',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=2564&auto=format&fit=crop',
    bio: 'Polyrhythmic Drum Programmer & Afrobeats Producer 🥁 Live talking drum sampling, analog drum machines & syncopated groove theory.',
    followers: 168000,
    following: 620,
    verified: true,
  },
  'user-yasmin': {
    id: 'user-yasmin',
    username: 'yasmin_webgpu',
    displayName: 'Yasmin Haddad',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop',
    bio: 'WebGPU Compute Shader Researcher & Fluid Dynamics Lead 🌊 Simulating 10 million Navier-Stokes fluid particles at 120 FPS in browser.',
    followers: 142300,
    following: 480,
    verified: true,
  },
  'user-mei': {
    id: 'user-mei',
    username: 'mei_tea',
    displayName: 'Mei Zhang',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=2564&auto=format&fit=crop',
    bio: 'Gongfu Tea Ceremony Master & Wood-Fired Ceramicist 🍵 Sourcing ancient wild arbor Pu-erh and crafting wood-fired purple clay teaware.',
    followers: 91400,
    following: 380,
    verified: true,
  },
  'user-alessia': {
    id: 'user-alessia',
    username: 'alessia_horology',
    displayName: 'Alessia Conti',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=2564&auto=format&fit=crop',
    bio: 'Master Watchmaker & Independent Tourbillon Creator ⌚ Hand-beveled titanium bridges, guilloché dials & high-beat chronometer movements.',
    followers: 138000,
    following: 270,
    verified: true,
  }
};

const BASE_POSTS: Post[] = [
  {
    id: 'post-1',
    authorId: 'user-anya',
    content: 'Just finished rendering the main biome for our upcoming open-world game! 🚀 Built with Unreal Engine 5.4 Nanite & Lumen. What do you think of the volumetric fog and atmospheric depth?',
    media: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600861194942-f883de0dfe96?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 18842,
    comments: 1184,
    shares: 898,
    resonanceScore: 0.98,
    x: 0, y: 0,
    createdAt: new Date(Date.now() - 1200000).toISOString(),
    likedByMe: true,
    savedByMe: true,
  },
  {
    id: 'post-2',
    authorId: 'user-marcus',
    content: 'Which AI architecture do you believe will define the next decade of spatial computing and autonomous agents?',
    likes: 21410,
    comments: 1620,
    shares: 1195,
    resonanceScore: 0.95,
    x: 150, y: 80,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    poll: {
      question: 'Which AI paradigm will dominate 2026–2030?',
      options: [
        { id: 'opt1', text: 'Real-time World Models (Spatial Generative)', votes: 9142 },
        { id: 'opt2', text: 'Neuromorphic On-Device Spiking Chips', votes: 4619 },
        { id: 'opt3', text: 'Hierarchical Multi-Agent Swarms', votes: 6195 },
        { id: 'opt4', text: 'Hybrid Neuro-Symbolic Reasoning', votes: 3410 },
      ],
      totalVotes: 23366,
      votedOptionId: 'opt1',
    },
  },
  {
    id: 'post-3',
    authorId: 'user-sophia',
    content: 'Minimalism isn\'t about having less — it\'s about making room for what truly matters. Here is my current design cockpit with a 38-inch curved OLED and tactile mechanical inputs. ☕💻',
    media: [
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 24190,
    comments: 1418,
    shares: 1192,
    resonanceScore: 0.96,
    x: -120, y: 180,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    likedByMe: true,
  },
  {
    id: 'post-4',
    authorId: 'user-elena',
    content: 'Late night modular synth recording session. Blending analog Moog filters with binaural field recordings of thunderstorms in Tokyo. 🎧🌧️ Cybernetic meditation.',
    media: [
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 12450,
    comments: 886,
    shares: 644,
    resonanceScore: 0.89,
    x: 220, y: -90,
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: 'post-5',
    authorId: 'user-chloe',
    content: 'Created a new generative shader with GLSL & Three.js. 100,000 particles responding to simulated gravitational fields and perlin noise turbulence. ✨🌌',
    media: [
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 31820,
    comments: 2185,
    shares: 2490,
    resonanceScore: 0.99,
    x: -240, y: -160,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    likedByMe: true,
  },
  {
    id: 'post-6',
    authorId: 'user-aditi',
    content: 'Excited to announce our upcoming **Multiverse Global Hackathon 2026**! 🚀 Over $50,000 in bounties for open-source AI agents, spatial UI widgets, and decentralized social protocols. Registration is now open on the Events tab!',
    media: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 36910,
    comments: 3180,
    shares: 4520,
    resonanceScore: 0.99,
    x: 80, y: -240,
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    likedByMe: true,
    savedByMe: true,
  },
  {
    id: 'post-7',
    authorId: 'user-jaxson',
    content: 'Freshly anodized 65% custom mechanical keyboard case in Cyber Deep Violet. Mirror-polished PVD brass weight, polycarbonate plate, and hand-lubed oil king switches. Sound test coming up! ⌨️💜',
    media: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 19780,
    comments: 1284,
    shares: 1145,
    resonanceScore: 0.92,
    x: -300, y: 120,
    createdAt: new Date(Date.now() - 25200000).toISOString(),
  },
  {
    id: 'post-8',
    authorId: 'user-kai',
    content: 'Just deployed our new Spatial WebXR demo running at a steady 90 FPS on standalone headsets. The future of the web is 3D, spatial, and persistent. 🌐🕶️',
    media: [
      'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 17940,
    comments: 1042,
    shares: 868,
    resonanceScore: 0.91,
    x: 320, y: 160,
    createdAt: new Date(Date.now() - 32400000).toISOString(),
  },
  {
    id: 'post-9',
    authorId: 'user-maya',
    content: 'What is your preferred consensus and privacy layer for decentralized identity systems in 2026?',
    likes: 12420,
    comments: 1110,
    shares: 784,
    resonanceScore: 0.88,
    x: 50, y: 300,
    createdAt: new Date(Date.now() - 39600000).toISOString(),
    poll: {
      question: 'Best privacy primitive for on-chain identity?',
      options: [
        { id: 'zk1', text: 'zk-SNARKs with Groth16 / Halo2', votes: 6120 },
        { id: 'zk2', text: 'zk-STARKs (Quantum Resistant)', votes: 4840 },
        { id: 'zk3', text: 'Fully Homomorphic Encryption (FHE)', votes: 3110 },
      ],
      totalVotes: 14070,
      votedOptionId: 'zk2',
    },
  },
  {
    id: 'post-10',
    authorId: 'user-zephyr',
    content: 'Ship fast, measure everything, and iterate with real users. We just hit 25,000 active monthly developers on our ambient developer CLI tool! Built with Rust and Tauri. 🦀💻',
    media: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 24820,
    comments: 1645,
    shares: 1380,
    resonanceScore: 0.94,
    x: -180, y: -320,
    createdAt: new Date(Date.now() - 46800000).toISOString(),
  },
  {
    id: 'post-11',
    authorId: 'user-valkyrie',
    content: 'Analyzed an emerging zero-day attack vector exploiting JIT compilation in WebAssembly engines. Full technical teardown and mitigation patch published on our security feed. Stay safe out there! 🛡️⚡',
    media: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 19120,
    comments: 1189,
    shares: 1140,
    resonanceScore: 0.93,
    x: 180, y: -300,
    createdAt: new Date(Date.now() - 54000000).toISOString(),
    likedByMe: true,
  },
  {
    id: 'post-12',
    authorId: 'user-tariq',
    content: 'We just folded a 450-amino-acid synthetic enzyme in under 12 seconds using distributed GPU tensors. The implications for custom biocatalysts and green manufacturing are unprecedented. 🧬🧪',
    media: [
      'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 16640,
    comments: 912,
    shares: 860,
    resonanceScore: 0.89,
    x: -320, y: -80,
    createdAt: new Date(Date.now() - 61200000).toISOString(),
  },
  {
    id: 'post-13',
    authorId: 'user-zara',
    content: 'Captured a 60-hour exposure of the Rosette Nebula using our remote observatory in Chile. Processing narrowband Ha, OIII, and SII filters revealed intricate stellar nurseries. 🌌🔭',
    media: [
      'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 29240,
    comments: 2112,
    shares: 2880,
    resonanceScore: 0.97,
    x: 280, y: 280,
    createdAt: new Date(Date.now() - 68400000).toISOString(),
    likedByMe: true,
  },
  {
    id: 'post-14',
    authorId: 'user-dante',
    content: 'In 2099, memories are currency and identity is fluid. Chapter 14 of "Echoes of Neo-Kyoto" is now live on the Articles section! 📖🏙️',
    media: [
      'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 14980,
    comments: 980,
    shares: 790,
    resonanceScore: 0.88,
    x: -160, y: 340,
    createdAt: new Date(Date.now() - 75600000).toISOString(),
  },
  {
    id: 'post-15',
    authorId: 'user-kavita',
    content: 'Live demonstration of non-invasive BCI controlling an interactive 3D spatial viewport with 98.6% intent fidelity. Zero implant required! 🧠⚡',
    media: [
      'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 22410,
    comments: 1580,
    shares: 1410,
    resonanceScore: 0.95,
    x: 360, y: -120,
    createdAt: new Date(Date.now() - 82800000).toISOString(),
    likedByMe: true,
  },
  {
    id: 'post-16',
    authorId: 'user-orion',
    content: 'Testing bipedal balance on rough gravel terrain using high-frequency torque control loops (2 kHz update rate). Dynamic stability achieved! 🤖🦾',
    media: [
      'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 24120,
    comments: 1690,
    shares: 1580,
    resonanceScore: 0.94,
    x: -280, y: 220,
    createdAt: new Date(Date.now() - 90000000).toISOString(),
  },
  {
    id: 'post-17',
    authorId: 'user-roy',
    content: 'Just deployed the 10/10 Peak UI overhaul on Yor Talks! 🌟 3D perspective tilt cards, cursor-guided ambient illumination, physics-based magnetic controls, and buttery route transitions. Test it out and let me know your thoughts!',
    media: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 48920,
    comments: 5840,
    shares: 7420,
    resonanceScore: 1.0,
    x: 0, y: -50,
    createdAt: new Date(Date.now() - 97200000).toISOString(),
    likedByMe: true,
    savedByMe: true,
  }
];

const EXTRA_AUTHORS = [
  'user-anya', 'user-marcus', 'user-sophia', 'user-elena', 'user-chloe', 'user-jaxson', 'user-kai', 'user-maya', 
  'user-zephyr', 'user-valkyrie', 'user-zara', 'user-kavita', 'user-orion', 'user-dante', 'user-liam', 'user-tariq', 
  'user-aravind', 'user-renata', 'user-kenji', 'user-leila', 'user-priya', 'user-lucas', 'user-vikram', 'user-nadia',
  'user-sakura', 'user-mateo', 'user-anika', 'user-yuki', 'user-clara', 'user-thorin', 'user-zane', 'user-valeria',
  'user-taro', 'user-milo', 'user-hina', 'user-gabriel', 'user-selena', 'user-alexei', 'user-fatima', 'user-dax',
  'user-charlotte', 'user-brennan', 'user-ayesha', 'user-soren', 'user-kofi', 'user-yasmin', 'user-mei', 'user-alessia'
];
const EXTRA_TOPICS = [
  { text: 'Exploring new shader passes for real-time volumetric atmospheric light scattering. The depth gradient creates an unforgettable mood.', img: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Sub-millisecond latency on websocket streaming protocols enables instantaneous peer collaboration in the Multiverse.', img: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Handcrafted anodized dials and magnetic encoder knobs on our latest physical audio control surface.', img: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Benchmarking on-device LLMs quantized to 4-bit AWQ with WebGPU shaders. 85 tokens/second directly inside Chrome!', img: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop' },
  { text: 'The interplay between light, darkness, and frosted glass panels in cyberpunk aesthetic interfaces.', img: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Decentralized state replication with conflict-free replicated data types (CRDTs) over peer-to-peer WebRTC.', img: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Precision CNC chamfering on 7075 aerospace aluminum. The tactile texture is unmatched.', img: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Binaural field recording on the rainy streets of Shinjuku at 3 AM. Uploading lossless FLAC stems to the audio lab.', img: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Zero-knowledge succinct proofs enabling private credential verification without revealing personal telemetry.', img: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Reinforcement learning policies trained in NVIDIA Isaac Sim transferring with zero sim-to-real gap on physical biped.', img: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Designing tactile feedback cues for high-precision micro-manipulations in immersive spatial viewports.', img: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Spectroscopic observation of hydrogen-alpha emission filaments in the Veil Nebula. Nature is the ultimate artist.', img: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Micro-electrode array recordings showing rapid motor cortex decoding during dual-finger trajectory intent tests.', img: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Modern CSS container units (cqw/cqh) combined with native CSS grid give total control over dynamic responsive cards.', img: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Building resilient local-first applications using SQLite WASM + OPFS persistence layer for instantaneous offline booting.', img: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Ray marching volumetric smoke in real time with WebGL 2.0. Achieving 120 FPS on Apple Silicon!', img: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop' },
  { text: 'How we tuned PID control loops on an 18-DOF quadruped robot for climbing 45-degree rocky inclines.', img: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1200&auto=format&fit=crop' },
  { text: 'The poetry of dark mode: deep obsidian tones (#030712) with 0.5px luminous borders create sublime depth.', img: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop' },
  { text: 'VCT Masters Grand Final clutch in 1v4! Hit the final 360 one-tap on Ascent. Highlights live on my Reels tab 🏆🎮', img: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop' },
  { text: 'New Neurofunk & Cyber-DNB track "Neon Overdrive" just dropped! 174 BPM rolling bassline with distorted 808s. Stems available in the soundboard 🎛️⚡', img: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Character concept sketch: "Cyber-Ronin 2099". Ink lines drawn in Clip Studio Paint and shaded with volumetric neon rim lighting 🎨✨', img: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Dropping our augmented runway collection "Synthetic Flora". Fiber-optic woven garments reacting in real-time to the wearer\'s heart rate 👗🌌', img: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Raga Bhairavi performed on a custom 22-string acoustic sitar running through a vintage Roland Space Echo tape delay 🪕🌧️', img: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Diving 2,000 ft vertical canyon at 140 km/h with our 6S custom carbon FPV drone. Raw uncompressed 8K ProRes 422 HQ 🛸💨', img: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Building an ultra-low latency WebAudio synthesizer directly in React with AudioWorklets and WebAssembly DSP filters. Pure 64-bit float audio pipeline! 🎧💻', img: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Comparing optical switch latency (0.02ms) vs traditional mechanical switches (5ms debounce). The competitive advantage in high-APM gaming is undeniable ⌨️⚡', img: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Night photography in Kabukicho under heavy drizzle. Leica M6 + 35mm Summicron shot at f/2.0 on Kodak Vision3 500T 📸🌧️', img: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Generative 3D printed sneaker concept with variable-density Voronoi lattice midsole. Weighs just 180 grams! 👟✨', img: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Siphon extraction of anaerobic fermented Panama Geisha at 93.5°C. Notes of bergamot, white peach and jasmine tea ☕🌸', img: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Wrote a custom NES sound driver running inside our WebAssembly retro game engine. 4 channels of pure 8-bit nostalgia 👾🕹️', img: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Rigging a 40-meter tall transformable mech in Blender 4.2 using inverse kinematics and dynamic spring damping constraints 🤖⚔️', img: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Descended 8,400 meters in our titanium pressure sphere. Discovered a new species of bioluminescent siphonophore! 🌊✨', img: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Analyzing Magnus Carlsen vs Hikaru Nakamura Queen\'s Gambit endgame with our custom 128-core neural chess cluster ♟️🧠', img: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Islamic girih tile tessellations animated with parametric shader uniforms. The symmetry of mathematical infinity 📐🕌', img: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Dyno tested the 20B 3-rotor turbo RX-7: 840 WHP at 9,200 RPM with pure ethanol E85 fuel map! 🏎️🔥', img: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Cutting a master lacquer disc on our vintage 1974 Neumann lathe. The warm harmonics of physical vinyl grooves 💿🎙️', img: 'https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Restored the original 65mm camera negative of 1968 classic film. 12K scan revealed breathtaking film grain texture 🎬🎞️', img: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Traditional Danish joinery: crafting a solid white oak dining table with zero screws or metal fasteners 🪑🪵', img: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Simulating 10,000,000 fluid particles in WebGPU using Compute Shaders and Spatial Hashing. Running smooth at 144 FPS! 🌊💻', img: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Wood-firing unglazed purple clay teapots in an ancient dragon kiln for 72 hours continuously at 1,300°C 🍵🔥', img: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=1200&auto=format&fit=crop' },
  { text: 'Hand-finishing the titanium cage of a flying tourbillon movement with black polish and 45° anglage chamfers ⌚💎', img: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop' }
];

const GENERATED_POSTS: Post[] = EXTRA_TOPICS.map((topic, i) => {
  const authorId = EXTRA_AUTHORS[i % EXTRA_AUTHORS.length];
  const offset = (i + 18) * 7200000;
  return {
    id: `post-gen-${i + 1}`,
    authorId,
    content: topic.text,
    media: [topic.img],
    likes: Math.floor(9800 + (i * 970)),
    comments: Math.floor(620 + (i * 74)),
    shares: Math.floor(510 + (i * 68)),
    resonanceScore: 0.85 + ((i % 15) * 0.01),
    x: Math.floor((Math.sin(i) * 350)),
    y: Math.floor((Math.cos(i) * 350)),
    createdAt: new Date(Date.now() - offset).toISOString(),
    likedByMe: i % 3 === 0,
    savedByMe: i % 4 === 0,
  };
});

export const MOCK_POSTS: Post[] = [...BASE_POSTS, ...GENERATED_POSTS];

export const MOCK_STORIES: Story[] = [
  {
    id: 'story-1',
    authorId: 'user-anya',
    mediaUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    expiresAt: new Date(Date.now() + 84600000).toISOString(),
    viewerIds: ['user-roy'],
    reactions: [{ userId: 'user-roy', emoji: '🔥' }],
  },
  {
    id: 'story-2',
    authorId: 'user-aditi',
    mediaUrl: '',
    type: 'text',
    textContent: 'Hackathon prep in full swing! Who is ready to build the future of AI & Social? 🚀✨',
    backgroundGradient: 'linear-gradient(135deg, #6366f1, #a855f7, #ec4899)',
    viewed: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    expiresAt: new Date(Date.now() + 82800000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-3',
    authorId: 'user-marcus',
    mediaUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 5400000).toISOString(),
    expiresAt: new Date(Date.now() + 81000000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-4',
    authorId: 'user-sophia',
    mediaUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: true,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    expiresAt: new Date(Date.now() + 79200000).toISOString(),
    viewerIds: ['user-roy'],
    reactions: [{ userId: 'user-roy', emoji: '❤️' }],
  },
  {
    id: 'story-5',
    authorId: 'user-elena',
    mediaUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: true,
    createdAt: new Date(Date.now() - 9000000).toISOString(),
    expiresAt: new Date(Date.now() + 77400000).toISOString(),
    viewerIds: ['user-roy'],
    reactions: [],
  },
  {
    id: 'story-6',
    authorId: 'user-jaxson',
    mediaUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    expiresAt: new Date(Date.now() + 75600000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-7',
    authorId: 'user-chloe',
    mediaUrl: '',
    type: 'text',
    textContent: 'New generative shaders dropping tonight! 🌌 Prepare your GPUs.',
    backgroundGradient: 'linear-gradient(135deg, #3b82f6, #8b5cf6, #ec4899)',
    viewed: false,
    createdAt: new Date(Date.now() - 12600000).toISOString(),
    expiresAt: new Date(Date.now() + 73800000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-8',
    authorId: 'user-valkyrie',
    mediaUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    expiresAt: new Date(Date.now() + 72000000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-9',
    authorId: 'user-zara',
    mediaUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 16200000).toISOString(),
    expiresAt: new Date(Date.now() + 70200000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-10',
    authorId: 'user-tariq',
    mediaUrl: '',
    type: 'text',
    textContent: 'Tensor simulation benchmark complete: 99.4% accuracy on de novo catalytic sites! 🧬✨',
    backgroundGradient: 'linear-gradient(135deg, #10b981, #06b6d4, #3b82f6)',
    viewed: false,
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    expiresAt: new Date(Date.now() + 68400000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-11',
    authorId: 'user-kavita',
    mediaUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 19800000).toISOString(),
    expiresAt: new Date(Date.now() + 66600000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-12',
    authorId: 'user-orion',
    mediaUrl: '',
    type: 'text',
    textContent: '2 kHz torque loops working flawlessly. Humanoid balance reaches new heights! 🦾🤖',
    backgroundGradient: 'linear-gradient(135deg, #f59e0b, #ef4444, #8b5cf6)',
    viewed: false,
    createdAt: new Date(Date.now() - 21600000).toISOString(),
    expiresAt: new Date(Date.now() + 64800000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-13',
    authorId: 'user-aravind',
    mediaUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 23400000).toISOString(),
    expiresAt: new Date(Date.now() + 63000000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-14',
    authorId: 'user-renata',
    mediaUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 25200000).toISOString(),
    expiresAt: new Date(Date.now() + 61200000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-15',
    authorId: 'user-kenji',
    mediaUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 27000000).toISOString(),
    expiresAt: new Date(Date.now() + 59400000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-16',
    authorId: 'user-sakura',
    mediaUrl: '',
    type: 'text',
    textContent: 'Streaming tonight at 8 PM JST! 🌸 Special announcement regarding our new 3D model debut!',
    backgroundGradient: 'linear-gradient(135deg, #ec4899, #f43f5e, #a855f7)',
    viewed: false,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
    expiresAt: new Date(Date.now() + 57600000).toISOString(),
    viewerIds: [],
    reactions: [],
  }
];

export const MOCK_COMMUNITIES: Community[] = [
  {
    id: 'comm-1',
    name: 'Spatial Computing & XR',
    description: 'The frontier of WebXR, Apple Vision Pro, Meta Quest, and 3D spatial computing interfaces.',
    coverUrl: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?q=80&w=800&auto=format&fit=crop',
    members: 48420,
    isMember: true,
    visibility: 'public',
    category: 'Technology',
    trending: true,
  },
  {
    id: 'comm-2',
    name: 'Generative AI & World Models',
    description: 'Deep discussions, research papers, and code implementations for multi-modal AI and generative models.',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    members: 94200,
    isMember: true,
    visibility: 'public',
    category: 'AI & Research',
    trending: true,
  },
  {
    id: 'comm-3',
    name: 'Cyberpunk & Ambient Aesthetics',
    description: 'Futuristic visual arts, neon architecture, moody soundscapes, and sci-fi aesthetic inspiration.',
    coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=800&auto=format&fit=crop',
    members: 116800,
    isMember: true,
    visibility: 'public',
    category: 'Art & Design',
    trending: true,
  },
  {
    id: 'comm-4',
    name: 'Modern UI/UX & Micro-Interactions',
    description: 'Design systems, tactile physics, framer motion recipes, and craft-driven web engineering.',
    coverUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=800&auto=format&fit=crop',
    members: 78100,
    isMember: true,
    visibility: 'public',
    category: 'Design',
    trending: false,
  },
  {
    id: 'comm-5',
    name: 'Modular Audio & Synth Lab',
    description: 'Eurorack synthesizers, sound design, binaural audio production, and electronic music synthesis.',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    members: 44890,
    isMember: false,
    visibility: 'public',
    category: 'Music & Audio',
    trending: false,
  },
  {
    id: 'comm-6',
    name: 'Custom Mech Keyboards & Hardware',
    description: 'Custom mechanical keyboards, CNC machining, custom PCB designs, switches, and artisan keycaps.',
    coverUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop',
    members: 61450,
    isMember: false,
    visibility: 'public',
    category: 'Hardware',
    trending: true,
  },
  {
    id: 'comm-7',
    name: 'Indie Builders & Solopreneurs',
    description: 'Founders building revenue-generating products in public, sharing metrics and micro-SaaS strategies.',
    coverUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800&auto=format&fit=crop',
    members: 74200,
    isMember: true,
    visibility: 'public',
    category: 'Startups',
    trending: false,
  },
  {
    id: 'comm-8',
    name: 'Radiant Esports & Tactical Gaming',
    description: 'Aim training routines, clutch breakdown clips, team scrimmage scrims, and tournament brackets.',
    coverUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    members: 142000,
    isMember: true,
    visibility: 'public',
    category: 'Gaming',
    trending: true,
  },
  {
    id: 'comm-9',
    name: 'Anime Concept Art & Manga Illustration',
    description: 'Digital ink drawing, lighting tutorials, visual novel assets, and high-res anime sketches.',
    coverUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    members: 189000,
    isMember: true,
    visibility: 'public',
    category: 'Art & Design',
    trending: true,
  },
  {
    id: 'comm-10',
    name: 'Digital Haute Couture & Wearable Tech',
    description: 'Augmented reality fashion runways, LED embedded garments, and 3D digital apparel drops.',
    coverUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
    members: 88400,
    isMember: false,
    visibility: 'public',
    category: 'Fashion',
    trending: true,
  },
  {
    id: 'comm-11',
    name: 'FPV Freestyle & High-Speed Drone Cinema',
    description: 'Custom 6S drone builds, PID tuning flight telemetry, ProRes color grading, and proximity dives.',
    coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=800&auto=format&fit=crop',
    members: 65100,
    isMember: true,
    visibility: 'public',
    category: 'Videography',
    trending: false,
  },
  {
    id: 'comm-12',
    name: 'Specialty Coffee & Extraction Chemistry',
    description: 'Single-origin anaerobic beans, water mineral profiling, burr alignment, and pour-over recipes.',
    coverUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=800&auto=format&fit=crop',
    members: 51200,
    isMember: false,
    visibility: 'public',
    category: 'Lifestyle',
    trending: false,
  },
  {
    id: 'comm-13',
    name: 'Arcade Modding & Fighting Games',
    description: 'Custom leverless fightsticks, Brook PCB firmware, Sanwa buttons, and frame-data labs.',
    coverUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=800&auto=format&fit=crop',
    members: 78900,
    isMember: true,
    visibility: 'public',
    category: 'Gaming',
    trending: false,
  },
  {
    id: 'comm-14',
    name: 'Quantum Computing & ZK Labs',
    description: 'Zero-knowledge proofs, homomorphic encryption, quantum algorithms and cryptography.',
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
    members: 42320,
    isMember: false,
    visibility: 'public',
    category: 'Science',
    trending: false,
  },
  {
    id: 'comm-15',
    name: 'Offensive Security & Red Teaming',
    description: 'Binary exploitation, web security, reverse engineering, and threat intelligence exchange.',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    members: 51400,
    isMember: true,
    visibility: 'public',
    category: 'Security',
    trending: true,
  },
  {
    id: 'comm-16',
    name: 'Computational Biology & Synthetic Bio',
    description: 'Protein design, CRISPR gene drives, molecular dynamics, and bioinformatics pipelines.',
    coverUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=800&auto=format&fit=crop',
    members: 37900,
    isMember: false,
    visibility: 'public',
    category: 'Biotech',
    trending: false,
  },
  {
    id: 'comm-17',
    name: 'Astrophotography & Deep Space Optics',
    description: 'Telescope imaging, nebula processing, star tracker calibration, and planetary spectroscopy.',
    coverUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=800&auto=format&fit=crop',
    members: 49800,
    isMember: true,
    visibility: 'public',
    category: 'Astronomy',
    trending: true,
  },
  {
    id: 'comm-18',
    name: 'Humanoid Robotics & Tendon Actuation',
    description: 'Dynamic humanoid locomotion, harmonic drive actuators, and reinforcement learning control.',
    coverUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=800&auto=format&fit=crop',
    members: 58900,
    isMember: true,
    visibility: 'public',
    category: 'Robotics',
    trending: true,
  }
];

export const MOCK_EVENTS: EventItem[] = [
  {
    id: 'event-1',
    hostId: 'user-aditi',
    title: 'Multiverse Global Hackathon 2026',
    description: '48-hour global online hackathon building the next generation of spatial AI agents and tactile web products. $50,000 in grand prize bounties.',
    coverUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1000&auto=format&fit=crop',
    category: 'Hackathon',
    startsAt: new Date(Date.now() + 604800000).toISOString(),
    location: 'Virtual / Metaverse Stage 1',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-anya', 'user-marcus', 'user-sophia'],
    interestedIds: ['user-elena', 'user-kai'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-2',
    hostId: 'user-marcus',
    title: 'Spatial AI & World Models Summit',
    description: 'Keynotes and live coding workshops from leading researchers in neural radiance fields and generative physical simulations.',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000&auto=format&fit=crop',
    category: 'Conference',
    startsAt: new Date(Date.now() + 1209600000).toISOString(),
    location: 'San Francisco, CA & Live Stream',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-anya', 'user-chloe'],
    interestedIds: ['user-maya'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-3',
    hostId: 'user-elena',
    title: 'Midnight Synthwave & Ambient Live Session',
    description: 'An immersive binaural audio broadcast featuring live modular synth performances and generative reactive visuals.',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1000&auto=format&fit=crop',
    category: 'Live Music',
    startsAt: new Date(Date.now() + 172800000).toISOString(),
    location: 'Yor Talks Live Stage A',
    isOnline: true,
    attendeeIds: ['user-roy'],
    interestedIds: ['user-kai', 'user-sophia'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-4',
    hostId: 'user-sophia',
    title: 'Design Systems Jam: Micro-Interactions in 2026',
    description: 'Live interactive teardown of modern tactile UI patterns, fluid motion physics, and accessible component architectures.',
    coverUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1000&auto=format&fit=crop',
    category: 'Design Workshop',
    startsAt: new Date(Date.now() + 345600000).toISOString(),
    location: 'Discord Stage & Yor Talks Stream',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-aditi'],
    interestedIds: ['user-zephyr'],
    rsvpStatus: 'interested',
  },
  {
    id: 'event-5',
    hostId: 'user-valkyrie',
    title: 'Defcon Multiverse CTF Invitational',
    description: '24-hour jeopardy and attack-defense cybersecurity challenge for elite binary exploitation and cryptography teams.',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1000&auto=format&fit=crop',
    category: 'Security CTF',
    startsAt: new Date(Date.now() + 864000000).toISOString(),
    location: 'Encrypted Matrix Network',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-maya'],
    interestedIds: ['user-liam'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-6',
    hostId: 'user-zara',
    title: 'Deep Sky Star Party & Live Telescope Stream',
    description: 'Join us live under the pristine dark skies of the Atacama Desert capturing the Carina and Tarantula Nebulae.',
    coverUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=1000&auto=format&fit=crop',
    category: 'Astronomy',
    startsAt: new Date(Date.now() + 432000000).toISOString(),
    location: 'Atacama Desert Observatory & Stream',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-dante'],
    interestedIds: ['user-chloe'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-7',
    hostId: 'user-orion',
    title: 'Robotics Control Systems Live Demo & Teardown',
    description: 'Deep dive into high-bandwidth EtherCAT motor drivers and dynamic stability algorithms on bipedal walking platforms.',
    coverUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1000&auto=format&fit=crop',
    category: 'Robotics Demo',
    startsAt: new Date(Date.now() + 518400000).toISOString(),
    location: 'Robotics Innovation Lab 4',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-kavita'],
    interestedIds: ['user-jaxson'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-8',
    hostId: 'user-aravind',
    title: 'Radiant Champions Invitational: 5v5 Grand Finals',
    description: 'The premier tactical FPS showdown with 16 elite rosters battling for the $100,000 championship trophy.',
    coverUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1000&auto=format&fit=crop',
    category: 'Esports Tournament',
    startsAt: new Date(Date.now() + 259200000).toISOString(),
    location: 'Seoul Esports Arena & Live 4K Stream',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-yuki'],
    interestedIds: ['user-kai'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-9',
    hostId: 'user-renata',
    title: 'Tokyo Underground: Cyber-DNB & Modular Live Rave',
    description: 'An all-night underground rave featuring 174 BPM Neurofunk, live analog drum machines, and audio-reactive laser projections.',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1000&auto=format&fit=crop',
    category: 'Live Music',
    startsAt: new Date(Date.now() + 604800000).toISOString(),
    location: 'Shibuya Warehouse 04 & Binaural Stream',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-elena', 'user-priya'],
    interestedIds: ['user-chloe'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-10',
    hostId: 'user-kenji',
    title: 'Neo-Tokyo Anime Art Expo & Live Speed-Paint',
    description: 'Exhibition of 100+ original cyberpunk anime illustration frames, character design masterclasses, and portfolio reviews.',
    coverUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop',
    category: 'Art Exhibition',
    startsAt: new Date(Date.now() + 777600000).toISOString(),
    location: 'Kyoto Digital Art Hall & VR Gallery',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-anya'],
    interestedIds: ['user-leila'],
    rsvpStatus: 'interested',
  }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sellerId: 'user-jaxson',
    title: 'Cyber Anodized 65% Aluminum Mechanical Keyboard',
    description: 'Handcrafted custom mechanical keyboard with CNC milled 6063 aluminum body, hot-swappable PCB, FR4 plate, and lubricated Gateron Oil King linear switches.',
    price: 349,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Hardware',
    condition: 'new',
    savedByMe: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'prod-2',
    sellerId: 'user-elena',
    title: 'Studio Reference Open-Back Planar Headphones',
    description: 'Audiophile grade planar magnetic studio monitors with ultra-low distortion and expansive soundstage. Balanced 4.4mm cable included.',
    price: 499,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Audio',
    condition: 'like-new',
    savedByMe: false,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'prod-3',
    sellerId: 'user-sophia',
    title: 'Solid Walnut Ergonomic Desk Monitor Stand with USB-C Hub',
    description: 'Precision handcrafted American walnut riser with integrated 100W PD passthrough USB-C dock and ambient warm LED strip.',
    price: 189,
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Workspace',
    condition: 'new',
    savedByMe: true,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'prod-4',
    sellerId: 'user-kai',
    title: 'Haptic VR Controller Grips & Spatial Tracker Set',
    description: 'Low-latency spatial 6DoF tracking pucks with integrated vibrotactile feedback for SteamVR and OpenXR platforms.',
    price: 220,
    images: [
      'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'VR / Gaming',
    condition: 'like-new',
    savedByMe: false,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 'prod-5',
    sellerId: 'user-chloe',
    title: '38-inch Ultrawide Curved OLED Creator Monitor',
    description: '144Hz 3840x1600 OLED panel with 99.8% DCI-P3 color gamut, hardware calibration, and Thunderbolt 4 single-cable connectivity.',
    price: 980,
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Displays',
    condition: 'like-new',
    savedByMe: true,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: 'prod-6',
    sellerId: 'user-zara',
    title: 'Apochromatic Refractor Telescope Lens 80mm f/6',
    description: 'Extra-low dispersion FPL-53 glass with carbon fiber tube and dual-speed linear track focuser.',
    price: 750,
    images: [
      'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Optics',
    condition: 'like-new',
    savedByMe: false,
    createdAt: new Date(Date.now() - 518400000).toISOString(),
  },
  {
    id: 'prod-7',
    sellerId: 'user-aravind',
    title: 'Radiant Ultralight Carbon Fiber 8K Hz Esports Gaming Mouse',
    description: '36-gram magnesium alloy honeycombed chassis, PixArt 3395 sensor, 8000 Hz true polling rate, and zero-latency wireless receiver.',
    price: 179,
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Gaming',
    condition: 'new',
    savedByMe: true,
    createdAt: new Date(Date.now() - 600000000).toISOString(),
  },
  {
    id: 'prod-8',
    sellerId: 'user-thorin',
    title: 'Hand-Forged 512-Layer Damascus Santoku Chef Knife',
    description: '1095 & 15N20 high-carbon folded steel with 62 HRC hardness, stabilized Turkish walnut burl handle, and hand-stitched leather sheath.',
    price: 380,
    images: [
      'https://images.unsplash.com/photo-1593618998160-e34014e67546?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Artisan',
    condition: 'new',
    savedByMe: false,
    createdAt: new Date(Date.now() - 700000000).toISOString(),
  },
  {
    id: 'prod-9',
    sellerId: 'user-lucas',
    title: 'Custom 6S FPV Carbon Racing Drone Kit with DJI O3 Air Unit',
    description: 'T-Motor F60 PRO V 1950KV brushless motors, SpeedyBee F7 v3 flight controller, and 4K 60FPS stabilized digital video transmission.',
    price: 620,
    images: [
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Drones',
    condition: 'like-new',
    savedByMe: true,
    createdAt: new Date(Date.now() - 800000000).toISOString(),
  }
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: 'art-1',
    authorId: 'user-roy',
    title: 'Designing for the Multiverse: Fluid Micro-Interactions & Spatial Polish',
    excerpt: 'How we engineered a 10/10 peak UI design system featuring 3D perspective cards, ambient luminous physics, and sub-millisecond transition smoothness.',
    content: `When building modern interactive platforms, visual polish is not decorative afterthought — it is the primary differentiator between utilitarian software and software that people fall in love with.

### The Physics of Tactility
Every digital element exists within a spatial continuum. By introducing subtle 3D perspective rotation (±6°) combined with cursor-aware dynamic lighting, users feel like they are directly manipulating tactile physical materials rather than passive pixels.

### Fluid Performance Over Heavy DOM
Achieving 60+ FPS while rendering complex particle fields, glassmorphism blurs, and animated borders requires strict GPU acceleration via CSS transform matrices, \`will-change\`, and isolated render contexts.`,
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    readTime: 6,
    claps: 24420,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    savedByMe: true,
    collection: 'Engineering & Design',
  },
  {
    id: 'art-2',
    authorId: 'user-marcus',
    title: 'From Static LLMs to Real-Time Spatial World Models',
    excerpt: 'A comprehensive survey on the transition from next-token autoregression to continuous 4D generative physical world simulations.',
    content: `The paradigm of AI is shifting rapidly from textual query-response cycles to real-time generative physics simulations. By predicting future latent states across spatial volumes, agents can plan multi-step manipulations in simulated physical environments before executing in the physical world.`,
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
    readTime: 10,
    claps: 39840,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    savedByMe: true,
    collection: 'Artificial Intelligence',
  },
  {
    id: 'art-3',
    authorId: 'user-elena',
    title: 'The Psychology of Ambient Sound Design in Virtual Spaces',
    excerpt: 'Exploring how psychoacoustic spatial audio and binaural micro-harmonics regulate focus and cognitive endurance during long creative sessions.',
    content: `Audio is the subconscious anchor of digital presence. When spatial cues accurately match visual horizon lines, the brain enters a flow state with significantly reduced cognitive friction.`,
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop',
    readTime: 5,
    claps: 28680,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    collection: 'Audio Architecture',
  },
  {
    id: 'art-4',
    authorId: 'user-valkyrie',
    title: 'Zero-Day Vulnerability Mitigation in Modern WebAssembly Engines',
    excerpt: 'An in-depth security analysis on side-channel memory leaks and speculative execution vulnerabilities in sandboxed WASM runtimes.',
    content: `As WebAssembly runtimes power edge functions and client-side high-performance applications, memory isolation guarantees must be validated against speculative execution side-channels. Here is how modern compilers implement dynamic canary boundaries.`,
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1200&auto=format&fit=crop',
    readTime: 8,
    claps: 31190,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    savedByMe: true,
    collection: 'Cybersecurity',
  },
  {
    id: 'art-5',
    authorId: 'user-dante',
    title: 'Neo-Kyoto 2099: Constructing Architecture for Digital Immortality',
    excerpt: 'A narrative exploration of sprawling vertical megalopolises, neon memory vaults, and the architecture of cybernetic consciousness.',
    content: `In Neo-Kyoto, glass towers pierce low-hanging chemical clouds while neural networks hum softly beneath rain-slicked pavement. When physical real estate ceases to expand, society expands upward into the clouds and inward into synthetic consciousness.`,
    coverUrl: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?q=80&w=1200&auto=format&fit=crop',
    readTime: 7,
    claps: 18840,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    collection: 'Sci-Fi Narrative',
  }
];

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'vid-1',
    authorId: 'user-anya',
    title: 'Unreal Engine 5.4 Nanite & Volumetric Cloud Breakdown',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-city-with-flying-cars-41551-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    views: 248400,
    likes: 31150,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-2',
    authorId: 'user-chloe',
    title: 'Generative Particle Simulation in Three.js & GLSL Shaders',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-41552-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=800&auto=format&fit=crop',
    views: 424200,
    likes: 68890,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-3',
    authorId: 'user-jaxson',
    title: 'Custom Mech Keyboard CNC Milling & Sound Test Demo',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-typing-on-a-laptop-keyboard-41554-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop',
    views: 319800,
    likes: 42120,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    type: 'standard',
  },
  {
    id: 'vid-4',
    authorId: 'user-kai',
    title: 'Spatial WebXR 90 FPS Rendering on Standalone Headsets',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-city-with-flying-cars-41551-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?q=80&w=800&auto=format&fit=crop',
    views: 249900,
    likes: 31480,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-5',
    authorId: 'user-zara',
    title: 'Time-Lapse: 12 Hours of Galactic Core Rotation over Andes',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-41552-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=800&auto=format&fit=crop',
    views: 348100,
    likes: 48920,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    type: 'standard',
  },
  {
    id: 'vid-6',
    authorId: 'user-aravind',
    title: 'Radiant 1v4 Clutch with Sheriff on Ascent A-Site 🏆🔥',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-game-animation-of-a-character-running-42996-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    views: 512000,
    likes: 89400,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-7',
    authorId: 'user-renata',
    title: 'Dropping "Cyber Overdrive" at Tokyo Underground Warehouse Rave 🎛️⚡',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-dj-mixing-music-in-a-club-41555-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop',
    views: 684200,
    likes: 124000,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-8',
    authorId: 'user-lucas',
    title: 'FPV High-Speed Proximity Dive into Active Volcanic Fissure 🛸🌋',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-a-mountain-valley-41556-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=800&auto=format&fit=crop',
    views: 892000,
    likes: 164200,
    createdAt: new Date(Date.now() - 57600000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-9',
    authorId: 'user-priya',
    title: 'Sitar Fusion with Analog Tape Echoes & 808 Sub-Bass 🪕🌧️',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-playing-acoustic-guitar-41557-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    views: 310400,
    likes: 54200,
    createdAt: new Date(Date.now() - 72000000).toISOString(),
    type: 'standard',
  },
  {
    id: 'vid-10',
    authorId: 'user-kenji',
    title: 'Speed Painting 8K Anime Cyberpunk Rooftop in Clip Studio Paint 🎨✨',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-artist-painting-on-a-tablet-41558-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    views: 428900,
    likes: 76500,
    createdAt: new Date(Date.now() - 96000000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-11',
    authorId: 'user-leila',
    title: 'Holographic LED Runway Show - Cyber Haute Couture 2026 👗✨',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-fashion-model-walking-on-runway-41559-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
    views: 541000,
    likes: 98100,
    createdAt: new Date(Date.now() - 120000000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-12',
    authorId: 'user-elena',
    title: 'Sound Design Breakdown: Crafting Cyberpunk Weapons & Sci-Fi Lasers 🎧💥',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-sound-engineer-working-on-mixer-41560-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=800&auto=format&fit=crop',
    views: 298400,
    likes: 41900,
    createdAt: new Date(Date.now() - 150000000).toISOString(),
    type: 'standard',
  },
  {
    id: 'vid-13',
    authorId: 'user-zane',
    title: 'Neon Tokyo Rain: 4K Anamorphic Cinematic Street Walk 📸🌧️',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-city-traffic-at-night-with-bokeh-41561-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=800&auto=format&fit=crop',
    views: 742000,
    likes: 114000,
    createdAt: new Date(Date.now() - 180000000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-14',
    authorId: 'user-selena',
    title: 'Live Cassette Tape Loop & Ethereal Darkwave Vocals 🎙️🖤',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-singer-recording-in-a-studio-41562-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=800&auto=format&fit=crop',
    views: 389000,
    likes: 62400,
    createdAt: new Date(Date.now() - 210000000).toISOString(),
    type: 'standard',
  },
  {
    id: 'vid-15',
    authorId: 'user-dax',
    title: '20B 3-Rotor Turbo RX-7 Dyno Pull & 9,200 RPM Flames 🔥🏎️',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-sports-car-racing-on-a-track-41563-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800&auto=format&fit=crop',
    views: 940000,
    likes: 182000,
    createdAt: new Date(Date.now() - 240000000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-16',
    authorId: 'user-valeria',
    title: 'Procedural Voronoi 3D Printed Sneaker: Bending & Stress Test 👟✨',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-3d-printing-machine-in-action-41564-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=800&auto=format&fit=crop',
    views: 462000,
    likes: 71900,
    createdAt: new Date(Date.now() - 270000000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-17',
    authorId: 'user-kofi',
    title: 'Syncopated Afrobeats Drum Breakdown on Vintage E-Mu SP-1200 🥁🔥',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-drummer-playing-live-in-a-studio-41565-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    views: 521000,
    likes: 89400,
    createdAt: new Date(Date.now() - 300000000).toISOString(),
    type: 'standard',
  },
  {
    id: 'vid-18',
    authorId: 'user-alessia',
    title: 'Micro-Horology: Hand-Assembling a Flying Tourbillon Cage under 20x Microscope ⌚💎',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-watchmaker-repairing-a-watch-41566-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop',
    views: 614000,
    likes: 104000,
    createdAt: new Date(Date.now() - 330000000).toISOString(),
    type: 'short',
  }
];

export const MOCK_LIVESTREAMS: LiveStream[] = [
  {
    id: 'stream-1',
    hostId: 'user-elena',
    title: 'Live Modular Synth & Ambient Generative Sound Session 🎧',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    kind: 'audio',
    status: 'live',
    viewers: 9242,
    startsAt: new Date().toISOString(),
    category: 'Music Production',
    guestIds: ['user-roy', 'user-kai'],
  },
  {
    id: 'stream-2',
    hostId: 'user-marcus',
    title: 'Building Realtime World Models live with PyTorch & WebGPU 🤖',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'live',
    viewers: 24840,
    startsAt: new Date().toISOString(),
    category: 'AI Research',
    guestIds: ['user-maya'],
  },
  {
    id: 'stream-3',
    hostId: 'user-chloe',
    title: 'Creative Coding: Live Three.js Shader Architecture',
    coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'scheduled',
    viewers: 0,
    startsAt: new Date(Date.now() + 86400000).toISOString(),
    category: 'Digital Art',
    guestIds: [],
  },
  {
    id: 'stream-4',
    hostId: 'user-valkyrie',
    title: 'Live Binary Exploitation & CTF Reverse Engineering 🛡️',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'live',
    viewers: 14120,
    startsAt: new Date().toISOString(),
    category: 'Cybersecurity',
    guestIds: ['user-liam'],
  },
  {
    id: 'stream-5',
    hostId: 'user-zara',
    title: 'Live Chilean Observatory Stream: Nebular Core Tracking 🔭',
    coverUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'live',
    viewers: 12940,
    startsAt: new Date().toISOString(),
    category: 'Astronomy',
    guestIds: ['user-dante'],
  },
  {
    id: 'stream-6',
    hostId: 'user-aravind',
    title: 'Radiant Rank 1 Solo Queue Grind: Road to 1000 RR 🏆🔥',
    coverUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'live',
    viewers: 48920,
    startsAt: new Date().toISOString(),
    category: 'Gaming',
    guestIds: ['user-yuki'],
  },
  {
    id: 'stream-7',
    hostId: 'user-renata',
    title: 'Berlin Boiler Room: 174 BPM Neurofunk & Cyber-Bass 🎛️⚡',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop',
    kind: 'audio',
    status: 'live',
    viewers: 31200,
    startsAt: new Date().toISOString(),
    category: 'Music Production',
    guestIds: ['user-elena', 'user-priya'],
  },
  {
    id: 'stream-8',
    hostId: 'user-sakura',
    title: 'Sakura Live: 3D Model Rigging Masterclass & Chill Q&A 🌸✨',
    coverUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'live',
    viewers: 64100,
    startsAt: new Date().toISOString(),
    category: 'VTuber & Animation',
    guestIds: ['user-kenji'],
  },
  {
    id: 'stream-9',
    hostId: 'user-kenji',
    title: 'Live 8K Speed Painting: "Rainy Shibuya 2099" 🎨🏙️',
    coverUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'scheduled',
    viewers: 0,
    startsAt: new Date(Date.now() + 172800000).toISOString(),
    category: 'Digital Art',
    guestIds: ['user-anya'],
  }
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-anya',
    participantIds: ['user-roy', 'user-anya'],
    lastMessage: {
      id: 'msg-1',
      conversationId: 'conv-anya',
      senderId: 'user-anya',
      content: 'Hey Ayush! Check out the volumetric fog lighting shaders I just pushed. Looking forward to your thoughts!',
      createdAt: new Date(Date.now() - 900000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'conv-aditi',
    participantIds: ['user-roy', 'user-aditi'],
    lastMessage: {
      id: 'msg-2',
      conversationId: 'conv-aditi',
      senderId: 'user-aditi',
      content: 'Hackathon landing page is ready for review! The theme selector and 3D banner look incredible.',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'conv-marcus',
    participantIds: ['user-roy', 'user-marcus'],
    lastMessage: {
      id: 'msg-3',
      conversationId: 'conv-marcus',
      senderId: 'user-marcus',
      content: 'Let’s sync tomorrow on the on-device WebGPU model inference pipeline.',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'conv-sophia',
    participantIds: ['user-roy', 'user-sophia'],
    lastMessage: {
      id: 'msg-4',
      conversationId: 'conv-sophia',
      senderId: 'user-sophia',
      content: 'The new collapsible sidebar and heart burst animations make the platform feel like a million bucks. 🔥',
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'conv-valkyrie',
    participantIds: ['user-roy', 'user-valkyrie'],
    lastMessage: {
      id: 'msg-5',
      conversationId: 'conv-valkyrie',
      senderId: 'user-valkyrie',
      content: 'Completed the security audit on our websocket connection tokens — all clean and encrypted!',
      createdAt: new Date(Date.now() - 259200000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
  }
];

export const MOCK_MESSAGES_BY_CONVERSATION: Record<string, Message[]> = {
  'conv-anya': [
    {
      id: 'msg-anya-1',
      conversationId: 'conv-anya',
      senderId: 'user-roy',
      content: 'Hey Anya, how is the biome rendering coming along?',
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      read: true,
    },
    {
      id: 'msg-anya-2',
      conversationId: 'conv-anya',
      senderId: 'user-anya',
      content: 'Just finished tuning Lumen and Nanite for the foliage assets! Looks super crisp.',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      read: true,
    },
    {
      id: 'msg-anya-3',
      conversationId: 'conv-anya',
      senderId: 'user-anya',
      content: 'Hey Ayush! Check out the volumetric fog lighting shaders I just pushed. Looking forward to your thoughts!',
      createdAt: new Date(Date.now() - 900000).toISOString(),
      read: true,
    }
  ],
  'conv-aditi': [
    {
      id: 'msg-aditi-1',
      conversationId: 'conv-aditi',
      senderId: 'user-roy',
      content: 'Let us finalize the $50k prize pool categories for the global hackathon today.',
      createdAt: new Date(Date.now() - 14400000).toISOString(),
      read: true,
    },
    {
      id: 'msg-aditi-2',
      conversationId: 'conv-aditi',
      senderId: 'user-aditi',
      content: 'Hackathon landing page is ready for review! The theme selector and 3D banner look incredible.',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      read: true,
    }
  ],
  'conv-marcus': [
    {
      id: 'msg-marcus-1',
      conversationId: 'conv-marcus',
      senderId: 'user-marcus',
      content: 'Let’s sync tomorrow on the on-device WebGPU model inference pipeline.',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      read: true,
    }
  ],
  'conv-sophia': [
    {
      id: 'msg-sophia-1',
      conversationId: 'conv-sophia',
      senderId: 'user-sophia',
      content: 'The new collapsible sidebar and heart burst animations make the platform feel like a million bucks. 🔥',
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      read: true,
    }
  ],
  'conv-valkyrie': [
    {
      id: 'msg-valk-1',
      conversationId: 'conv-valkyrie',
      senderId: 'user-roy',
      content: 'Hey Valkyrie, let us know once the token refresh audit is complete.',
      createdAt: new Date(Date.now() - 345600000).toISOString(),
      read: true,
    },
    {
      id: 'msg-valk-2',
      conversationId: 'conv-valkyrie',
      senderId: 'user-valkyrie',
      content: 'Completed the security audit on our websocket connection tokens — all clean and encrypted!',
      createdAt: new Date(Date.now() - 259200000).toISOString(),
      read: true,
    }
  ]
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'like',
    title: 'New Post Reaction',
    message: 'Anya, Sophia Chen, and 384 others liked your post "Designing for the Multiverse".',
    actorId: 'user-anya',
    targetId: 'post-1',
    read: false,
    createdAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'notif-2',
    type: 'follow',
    title: 'New Follower',
    message: 'Marcus Vance started following you.',
    actorId: 'user-marcus',
    targetId: 'user-roy',
    read: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'mention',
    title: 'Mentioned in Post',
    message: 'Aditi Singh mentioned you in "Multiverse Global Hackathon 2026".',
    actorId: 'user-aditi',
    targetId: 'post-6',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-4',
    type: 'comment',
    title: 'New Comment',
    message: 'Sophia Chen commented on your profile wall: "Love the ambient design!"',
    actorId: 'user-sophia',
    targetId: 'user-roy',
    read: true,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'notif-5',
    type: 'community',
    title: 'Community Trending',
    message: 'Spatial Computing & XR reached 60,000 members!',
    actorId: 'user-anya',
    targetId: 'comm-1',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'notif-6',
    type: 'event',
    title: 'Event Reminder',
    message: 'Midnight Synthwave & Ambient Live Session starts in 2 days.',
    actorId: 'user-elena',
    targetId: 'event-3',
    read: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'notif-7',
    type: 'star',
    title: 'Achievement Unlocked',
    message: 'You unlocked "Spatial Pioneer" (+150 XP)!',
    actorId: 'user-roy',
    targetId: null,
    read: true,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  }
];
