import type { User, Post, Story, Community, EventItem, Product, Article, Video, LiveStream, Conversation, Message, Notification } from './store';

export const MOCK_USERS: Record<string, User> = {
  'user-roy': {
    id: 'user-roy',
    username: 'yorayriniwnl',
    displayName: 'Ayush Roy',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop',
    bio: 'Founder & Full-Stack Architect @ Yor Talks. Building ambient systems, spatial computing tools, and high-performance product surfaces. 🚀⚡',
    followers: 2420,
    following: 180,
    followingIds: ['user-anya', 'user-aditi', 'user-marcus', 'user-sophia', 'user-elena', 'user-kai'],
    verified: true,
  },
  'user-anya': {
    id: 'user-anya',
    username: 'anyaa_yaps',
    displayName: 'Anya Sharma',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2564&auto=format&fit=crop',
    bio: '3D World Builder & Unreal Engine 5.4 Enthusiast 🎮✨ Exploring procedural environments, volumetric lighting & shader graphs.',
    followers: 6890,
    following: 340,
    followingIds: ['user-roy', 'user-marcus', 'user-chloe'],
    verified: true,
  },
  'user-aditi': {
    id: 'user-aditi',
    username: 'aditi_cofounder',
    displayName: 'Aditi Singh',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?q=80&w=2564&auto=format&fit=crop',
    bio: 'Co-Founder @ Yor Talks & Yor Zenith 🌌 Multimodal AI, community ecosystems & modern aesthetics. Organizing Global Hackathon 2026!',
    followers: 5820,
    following: 210,
    followingIds: ['user-roy', 'user-anya', 'user-elena'],
    verified: true,
  },
  'user-marcus': {
    id: 'user-marcus',
    username: 'marcus_ai',
    displayName: 'Marcus Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2564&auto=format&fit=crop',
    bio: 'AI Researcher & Spatial Computing Lead 🤖 Neuromorphic architecture, world models & real-time perception.',
    followers: 12450,
    following: 420,
    followingIds: ['user-roy', 'user-sophia', 'user-maya'],
    verified: true,
  },
  'user-elena': {
    id: 'user-elena',
    username: 'elena_audio',
    displayName: 'Elena Rostova',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=2564&auto=format&fit=crop',
    bio: 'Audio Architect & Sound Synthesist 🎧 Modular synth lover, generative ambient textures & binaural soundscapes.',
    followers: 8710,
    following: 510,
    followingIds: ['user-roy', 'user-kai'],
    verified: true,
  },
  'user-sophia': {
    id: 'user-sophia',
    username: 'sophia_ui',
    displayName: 'Sophia Chen',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=2564&auto=format&fit=crop',
    bio: 'Design Systems Lead @ Multiverse Studio. Minimalist typography, micro-interactions & tactile interfaces. ☕📐',
    followers: 18400,
    following: 380,
    followingIds: ['user-roy', 'user-aditi'],
    verified: true,
  },
  'user-kai': {
    id: 'user-kai',
    username: 'kai_thorne',
    displayName: 'Kai Thorne',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2564&auto=format&fit=crop',
    bio: 'Cybernetic Game Director 🎮 Building immersive VR/XR experiences with cutting-edge shaders and physics.',
    followers: 7310,
    following: 290,
    followingIds: ['user-roy', 'user-anya'],
    verified: true,
  },
  'user-maya': {
    id: 'user-maya',
    username: 'maya_lin',
    displayName: 'Maya Lin',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2564&auto=format&fit=crop',
    bio: 'Quantum Computing & Zero-Knowledge Cryptography enthusiast 🌌 Exploring lattice cryptography & post-quantum security.',
    followers: 6120,
    following: 190,
    verified: true,
  },
  'user-jaxson': {
    id: 'user-jaxson',
    username: 'jaxson_hardware',
    displayName: 'Jaxson Reed',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2564&auto=format&fit=crop',
    bio: 'Custom Hardware Artisan & Mech Keyboard Creator ⌨️ CNC milling, anodized aluminum cases & custom PCB layouts.',
    followers: 11210,
    following: 460,
    verified: true,
  },
  'user-chloe': {
    id: 'user-chloe',
    username: 'chloe_visuals',
    displayName: 'Chloe Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=2564&auto=format&fit=crop',
    bio: 'Generative Art Director & Motion Designer 🎨 Transforming mathematical equations into living digital canvases.',
    followers: 21300,
    following: 610,
    verified: true,
  },
  'user-zephyr': {
    id: 'user-zephyr',
    username: 'zephyr_voss',
    displayName: 'Zephyr Voss',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=2564&auto=format&fit=crop',
    bio: 'Indie Hacker & Solopreneur 🛠️ Bootstrapping developer tools, CLI utilities and micro-SaaS products. Rust & TypeScript.',
    followers: 9890,
    following: 340,
    verified: false,
  },
  'user-liam': {
    id: 'user-liam',
    username: 'liam_devops',
    displayName: 'Liam O’Connor',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2564&auto=format&fit=crop',
    bio: 'Distributed Systems & Cloud Architecture Engineer ☁️ Kubernetes clusters, eBPF telemetry & zero-latency edge networks.',
    followers: 8430,
    following: 280,
    verified: true,
  },
  'user-valkyrie': {
    id: 'user-valkyrie',
    username: 'valk_cyber',
    displayName: 'Valkyrie Ray',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=2564&auto=format&fit=crop',
    bio: 'Offensive Security Researcher & Reverse Engineer 🛡️ Binary exploitation, smart contract audits & hardware security.',
    followers: 14900,
    following: 320,
    verified: true,
  },
  'user-tariq': {
    id: 'user-tariq',
    username: 'tariq_biotech',
    displayName: 'Dr. Tariq Al-Mansoor',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=2564&auto=format&fit=crop',
    bio: 'Computational Biologist & Protein Folding Architect 🧬 Simulating molecular dynamics with neural tensor networks.',
    followers: 7210,
    following: 150,
    verified: true,
  }
};

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    authorId: 'user-anya',
    content: 'Just finished rendering the main biome for our upcoming open-world game! 🚀 Built with Unreal Engine 5.4 Nanite & Lumen. What do you think of the volumetric fog and atmospheric depth?',
    media: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600861194942-f883de0dfe96?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 2842,
    comments: 184,
    shares: 98,
    resonanceScore: 0.98,
    x: 0, y: 0,
    createdAt: new Date(Date.now() - 1200000).toISOString(),
    likedByMe: true,
    savedByMe: true,
  },
  {
    id: 'post-2',
    authorId: 'user-marcus',
    content: 'Which AI architecture do you believe will define the next decade of spatial computing and autonomous agents?',
    likes: 3410,
    comments: 420,
    shares: 195,
    resonanceScore: 0.95,
    x: 150, y: 80,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    poll: {
      question: 'Which AI paradigm will dominate 2026–2030?',
      options: [
        { id: 'opt1', text: 'Real-time World Models (Spatial Generative)', votes: 1242 },
        { id: 'opt2', text: 'Neuromorphic On-Device Spiking Chips', votes: 619 },
        { id: 'opt3', text: 'Hierarchical Multi-Agent Swarms', votes: 895 },
        { id: 'opt4', text: 'Hybrid Neuro-Symbolic Reasoning', votes: 410 },
      ],
      totalVotes: 3166,
      votedOptionId: 'opt1',
    },
  },
  {
    id: 'post-3',
    authorId: 'user-sophia',
    content: 'Minimalism isn\'t about having less — it\'s about making room for what truly matters. Here is my current design cockpit with a 38-inch curved OLED and tactile mechanical inputs. ☕💻',
    media: [
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 4190,
    comments: 318,
    shares: 212,
    resonanceScore: 0.96,
    x: -120, y: 180,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    likedByMe: true,
  },
  {
    id: 'post-4',
    authorId: 'user-elena',
    content: 'Late night modular synth recording session. Blending analog Moog filters with binaural field recordings of thunderstorms in Tokyo. 🎧🌧️ Cybernetic meditation.',
    media: [
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 1850,
    comments: 116,
    shares: 64,
    resonanceScore: 0.89,
    x: 220, y: -90,
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: 'post-5',
    authorId: 'user-chloe',
    content: 'Created a new generative shader with GLSL & Three.js. 100,000 particles responding to simulated gravitational fields and perlin noise turbulence. ✨🌌',
    media: [
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 5820,
    comments: 385,
    shares: 490,
    resonanceScore: 0.99,
    x: -240, y: -160,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    likedByMe: true,
  },
  {
    id: 'post-6',
    authorId: 'user-aditi',
    content: 'Excited to announce our upcoming **Multiverse Global Hackathon 2026**! 🚀 Over $50,000 in bounties for open-source AI agents, spatial UI widgets, and decentralized social protocols. Registration is now open on the Events tab!',
    media: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 7410,
    comments: 680,
    shares: 920,
    resonanceScore: 0.99,
    x: 80, y: -240,
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    likedByMe: true,
    savedByMe: true,
  },
  {
    id: 'post-7',
    authorId: 'user-jaxson',
    content: 'Freshly anodized 65% custom mechanical keyboard case in Cyber Deep Violet. Mirror-polished PVD brass weight, polycarbonate plate, and hand-lubed oil king switches. Sound test coming up! ⌨️💜',
    media: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 3780,
    comments: 284,
    shares: 165,
    resonanceScore: 0.92,
    x: -300, y: 120,
    createdAt: new Date(Date.now() - 25200000).toISOString(),
  },
  {
    id: 'post-8',
    authorId: 'user-kai',
    content: 'Just deployed our new Spatial WebXR demo running at a steady 90 FPS on standalone headsets. The future of the web is 3D, spatial, and persistent. 🌐🕶️',
    media: [
      'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 2940,
    comments: 172,
    shares: 118,
    resonanceScore: 0.91,
    x: 320, y: 160,
    createdAt: new Date(Date.now() - 32400000).toISOString(),
  },
  {
    id: 'post-9',
    authorId: 'user-maya',
    content: 'What is your preferred consensus and privacy layer for decentralized identity systems in 2026?',
    likes: 1820,
    comments: 240,
    shares: 84,
    resonanceScore: 0.88,
    x: 50, y: 300,
    createdAt: new Date(Date.now() - 39600000).toISOString(),
    poll: {
      question: 'Best privacy primitive for on-chain identity?',
      options: [
        { id: 'zk1', text: 'zk-SNARKs with Groth16 / Halo2', votes: 820 },
        { id: 'zk2', text: 'zk-STARKs (Quantum Resistant)', votes: 640 },
        { id: 'zk3', text: 'Fully Homomorphic Encryption (FHE)', votes: 410 },
      ],
      totalVotes: 1870,
      votedOptionId: 'zk2',
    },
  },
  {
    id: 'post-10',
    authorId: 'user-zephyr',
    content: 'Ship fast, measure everything, and iterate with real users. We just hit 25,000 active monthly developers on our ambient developer CLI tool! Built with Rust and Tauri. 🦀💻',
    media: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 4820,
    comments: 345,
    shares: 280,
    resonanceScore: 0.94,
    x: -180, y: -320,
    createdAt: new Date(Date.now() - 46800000).toISOString(),
  },
  {
    id: 'post-11',
    authorId: 'user-valkyrie',
    content: 'Analyzed an emerging zero-day attack vector exploiting JIT compilation in WebAssembly engines. Full technical teardown and mitigation patch published on our security feed. Stay safe out there! 🛡️⚡',
    media: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 3120,
    comments: 189,
    shares: 240,
    resonanceScore: 0.93,
    x: 180, y: -300,
    createdAt: new Date(Date.now() - 54000000).toISOString(),
    likedByMe: true,
  },
  {
    id: 'post-12',
    authorId: 'user-tariq',
    content: 'We just folded a 450-amino-acid synthetic enzyme in under 12 seconds using distributed GPU tensors. The implications for custom biocatalysts and green manufacturing are unprecedented. 🧬🧪',
    media: [
      'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 2640,
    comments: 142,
    shares: 110,
    resonanceScore: 0.89,
    x: -320, y: -80,
    createdAt: new Date(Date.now() - 61200000).toISOString(),
  },
  {
    id: 'post-13',
    authorId: 'user-liam',
    content: 'Zero-downtime database migration across 4 global Kubernetes clusters completed in 8ms with zero packet drop. Multi-region Raft consensus is pure magic when configured properly. ☁️🛠️',
    likes: 2190,
    comments: 130,
    shares: 85,
    resonanceScore: 0.87,
    x: 290, y: -190,
    createdAt: new Date(Date.now() - 68400000).toISOString(),
  },
  {
    id: 'post-14',
    authorId: 'user-roy',
    content: 'Just deployed the 10/10 Peak UI overhaul on Yor Talks! 🌟 3D perspective tilt cards, cursor-guided ambient illumination, physics-based magnetic controls, and buttery route transitions. Test it out and let me know your thoughts!',
    media: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop'
    ],
    likes: 8920,
    comments: 940,
    shares: 1120,
    resonanceScore: 1.0,
    x: 0, y: -50,
    createdAt: new Date(Date.now() - 75600000).toISOString(),
    likedByMe: true,
    savedByMe: true,
  },
  {
    id: 'post-15',
    authorId: 'user-sophia',
    content: 'What is your favorite modern CSS feature that replaced tons of JavaScript in your stack?',
    likes: 3410,
    comments: 480,
    shares: 190,
    resonanceScore: 0.94,
    x: -80, y: 260,
    createdAt: new Date(Date.now() - 82800000).toISOString(),
    poll: {
      question: 'Most impactful modern CSS superpower?',
      options: [
        { id: 'css1', text: '@property & Houdini Animations', votes: 940 },
        { id: 'css2', text: 'Container Queries & :has() Selector', votes: 1420 },
        { id: 'css3', text: 'Subgrid & Native CSS Nesting', votes: 680 },
        { id: 'css4', text: 'View Transitions API', votes: 1120 },
      ],
      totalVotes: 4160,
      votedOptionId: 'css2',
    },
  }
];

export const MOCK_STORIES: Story[] = [
  {
    id: 'story-1',
    authorId: 'user-anya',
    mediaUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    expiresAt: new Date(Date.now() + 84600000).toISOString(),
    viewerIds: ['user-roy'],
    reactions: [{ userId: 'user-roy', emoji: '🔥' }],
  },
  {
    id: 'story-2',
    authorId: 'user-aditi',
    mediaUrl: '',
    type: 'text',
    textContent: 'Hackathon prep in full swing! Who is ready to build the future of AI & Social? 🚀✨',
    backgroundGradient: 'linear-gradient(135deg, #6366f1, #a855f7, #ec4899)',
    viewed: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    expiresAt: new Date(Date.now() + 82800000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-3',
    authorId: 'user-marcus',
    mediaUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 5400000).toISOString(),
    expiresAt: new Date(Date.now() + 81000000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-4',
    authorId: 'user-sophia',
    mediaUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: true,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    expiresAt: new Date(Date.now() + 79200000).toISOString(),
    viewerIds: ['user-roy'],
    reactions: [{ userId: 'user-roy', emoji: '❤️' }],
  },
  {
    id: 'story-5',
    authorId: 'user-elena',
    mediaUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: true,
    createdAt: new Date(Date.now() - 9000000).toISOString(),
    expiresAt: new Date(Date.now() + 77400000).toISOString(),
    viewerIds: ['user-roy'],
    reactions: [],
  },
  {
    id: 'story-6',
    authorId: 'user-jaxson',
    mediaUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    expiresAt: new Date(Date.now() + 75600000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-7',
    authorId: 'user-chloe',
    mediaUrl: '',
    type: 'text',
    textContent: 'New generative shaders dropping tonight! 🌌 Prepare your GPUs.',
    backgroundGradient: 'linear-gradient(135deg, #3b82f6, #8b5cf6, #ec4899)',
    viewed: false,
    createdAt: new Date(Date.now() - 12600000).toISOString(),
    expiresAt: new Date(Date.now() + 73800000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-8',
    authorId: 'user-valkyrie',
    mediaUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    type: 'image',
    viewed: false,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    expiresAt: new Date(Date.now() + 72000000).toISOString(),
    viewerIds: [],
    reactions: [],
  },
  {
    id: 'story-9',
    authorId: 'user-tariq',
    mediaUrl: '',
    type: 'text',
    textContent: 'Tensor simulation benchmark complete: 99.4% accuracy on de novo catalytic sites! 🧬✨',
    backgroundGradient: 'linear-gradient(135deg, #10b981, #06b6d4, #3b82f6)',
    viewed: false,
    createdAt: new Date(Date.now() - 16200000).toISOString(),
    expiresAt: new Date(Date.now() + 70200000).toISOString(),
    viewerIds: [],
    reactions: [],
  }
];

export const MOCK_COMMUNITIES: Community[] = [
  {
    id: 'comm-1',
    name: 'Spatial Computing & XR',
    description: 'The frontier of WebXR, Apple Vision Pro, Meta Quest, and 3D spatial computing interfaces.',
    coverUrl: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?q=80&w=800&auto=format&fit=crop',
    members: 12420,
    isMember: true,
    visibility: 'public',
    category: 'Technology',
    trending: true,
  },
  {
    id: 'comm-2',
    name: 'Generative AI & World Models',
    description: 'Deep discussions, research papers, and code implementations for multi-modal AI and generative models.',
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    members: 24200,
    isMember: true,
    visibility: 'public',
    category: 'AI & Research',
    trending: true,
  },
  {
    id: 'comm-3',
    name: 'Cyberpunk & Ambient Aesthetics',
    description: 'Futuristic visual arts, neon architecture, moody soundscapes, and sci-fi aesthetic inspiration.',
    coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=800&auto=format&fit=crop',
    members: 29800,
    isMember: true,
    visibility: 'public',
    category: 'Art & Design',
    trending: true,
  },
  {
    id: 'comm-4',
    name: 'Modern UI/UX & Micro-Interactions',
    description: 'Design systems, tactile physics, framer motion recipes, and craft-driven web engineering.',
    coverUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=800&auto=format&fit=crop',
    members: 18100,
    isMember: true,
    visibility: 'public',
    category: 'Design',
    trending: false,
  },
  {
    id: 'comm-5',
    name: 'Modular Audio & Synth Lab',
    description: 'Eurorack synthesizers, sound design, binaural audio production, and electronic music synthesis.',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    members: 9890,
    isMember: false,
    visibility: 'public',
    category: 'Music & Audio',
    trending: false,
  },
  {
    id: 'comm-6',
    name: 'Custom Mech Keyboards & Hardware',
    description: 'Custom mechanical keyboards, CNC machining, custom PCB designs, switches, and artisan keycaps.',
    coverUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop',
    members: 14450,
    isMember: false,
    visibility: 'public',
    category: 'Hardware',
    trending: true,
  },
  {
    id: 'comm-7',
    name: 'Indie Builders & Solopreneurs',
    description: 'Founders building revenue-generating products in public, sharing metrics and micro-SaaS strategies.',
    coverUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800&auto=format&fit=crop',
    members: 16200,
    isMember: true,
    visibility: 'public',
    category: 'Startups',
    trending: false,
  },
  {
    id: 'comm-8',
    name: 'Quantum Computing & ZK Labs',
    description: 'Zero-knowledge proofs, homomorphic encryption, quantum algorithms and cryptography.',
    coverUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
    members: 7320,
    isMember: false,
    visibility: 'public',
    category: 'Science',
    trending: false,
  },
  {
    id: 'comm-9',
    name: 'Offensive Security & Red Teaming',
    description: 'Binary exploitation, web security, reverse engineering, and threat intelligence exchange.',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    members: 11400,
    isMember: true,
    visibility: 'public',
    category: 'Security',
    trending: true,
  },
  {
    id: 'comm-10',
    name: 'Computational Biology & Synthetic Bio',
    description: 'Protein design, CRISPR gene drives, molecular dynamics, and bioinformatics pipelines.',
    coverUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=800&auto=format&fit=crop',
    members: 5900,
    isMember: false,
    visibility: 'public',
    category: 'Biotech',
    trending: false,
  }
];

export const MOCK_EVENTS: EventItem[] = [
  {
    id: 'event-1',
    hostId: 'user-aditi',
    title: 'Multiverse Global Hackathon 2026',
    description: '48-hour global online hackathon building the next generation of spatial AI agents and tactile web products. $50,000 in grand prize bounties.',
    coverUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1000&auto=format&fit=crop',
    category: 'Hackathon',
    startsAt: new Date(Date.now() + 604800000).toISOString(),
    location: 'Virtual / Metaverse Stage 1',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-anya', 'user-marcus', 'user-sophia'],
    interestedIds: ['user-elena', 'user-kai'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-2',
    hostId: 'user-marcus',
    title: 'Spatial AI & World Models Summit',
    description: 'Keynotes and live coding workshops from leading researchers in neural radiance fields and generative physical simulations.',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1000&auto=format&fit=crop',
    category: 'Conference',
    startsAt: new Date(Date.now() + 1209600000).toISOString(),
    location: 'San Francisco, CA & Live Stream',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-anya', 'user-chloe'],
    interestedIds: ['user-maya'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-3',
    hostId: 'user-elena',
    title: 'Midnight Synthwave & Ambient Live Session',
    description: 'An immersive binaural audio broadcast featuring live modular synth performances and generative reactive visuals.',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1000&auto=format&fit=crop',
    category: 'Live Music',
    startsAt: new Date(Date.now() + 172800000).toISOString(),
    location: 'Yor Talks Live Stage A',
    isOnline: true,
    attendeeIds: ['user-roy'],
    interestedIds: ['user-kai', 'user-sophia'],
    rsvpStatus: 'going',
  },
  {
    id: 'event-4',
    hostId: 'user-sophia',
    title: 'Design Systems Jam: Micro-Interactions in 2026',
    description: 'Live interactive teardown of modern tactile UI patterns, fluid motion physics, and accessible component architectures.',
    coverUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1000&auto=format&fit=crop',
    category: 'Design Workshop',
    startsAt: new Date(Date.now() + 345600000).toISOString(),
    location: 'Discord Stage & Yor Talks Stream',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-aditi'],
    interestedIds: ['user-zephyr'],
    rsvpStatus: 'interested',
  },
  {
    id: 'event-5',
    hostId: 'user-valkyrie',
    title: 'Defcon Multiverse CTF Invitational',
    description: '24-hour jeopardy and attack-defense cybersecurity challenge for elite binary exploitation and cryptography teams.',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1000&auto=format&fit=crop',
    category: 'Security CTF',
    startsAt: new Date(Date.now() + 864000000).toISOString(),
    location: 'Encrypted Matrix Network',
    isOnline: true,
    attendeeIds: ['user-roy', 'user-maya'],
    interestedIds: ['user-liam'],
    rsvpStatus: 'going',
  }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sellerId: 'user-jaxson',
    title: 'Cyber Anodized 65% Aluminum Mechanical Keyboard',
    description: 'Handcrafted custom mechanical keyboard with CNC milled 6063 aluminum body, hot-swappable PCB, FR4 plate, and lubricated Gateron Oil King linear switches.',
    price: 349,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Hardware',
    condition: 'new',
    savedByMe: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'prod-2',
    sellerId: 'user-elena',
    title: 'Studio Reference Open-Back Planar Headphones',
    description: 'Audiophile grade planar magnetic studio monitors with ultra-low distortion and expansive soundstage. Balanced 4.4mm cable included.',
    price: 499,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Audio',
    condition: 'like-new',
    savedByMe: false,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'prod-3',
    sellerId: 'user-sophia',
    title: 'Solid Walnut Ergonomic Desk Monitor Stand with USB-C Hub',
    description: 'Precision handcrafted American walnut riser with integrated 100W PD passthrough USB-C dock and ambient warm LED strip.',
    price: 189,
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Workspace',
    condition: 'new',
    savedByMe: true,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'prod-4',
    sellerId: 'user-kai',
    title: 'Haptic VR Controller Grips & Spatial Tracker Set',
    description: 'Low-latency spatial 6DoF tracking pucks with integrated vibrotactile feedback for SteamVR and OpenXR platforms.',
    price: 220,
    images: [
      'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'VR / Gaming',
    condition: 'like-new',
    savedByMe: false,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 'prod-5',
    sellerId: 'user-chloe',
    title: '38-inch Ultrawide Curved OLED Creator Monitor',
    description: '144Hz 3840x1600 OLED panel with 99.8% DCI-P3 color gamut, hardware calibration, and Thunderbolt 4 single-cable connectivity.',
    price: 980,
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1000&auto=format&fit=crop'
    ],
    category: 'Displays',
    condition: 'like-new',
    savedByMe: true,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  }
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: 'art-1',
    authorId: 'user-roy',
    title: 'Designing for the Multiverse: Fluid Micro-Interactions & Spatial Polish',
    excerpt: 'How we engineered a 10/10 peak UI design system featuring 3D perspective cards, ambient luminous physics, and sub-millisecond transition smoothness.',
    content: `When building modern interactive platforms, visual polish is not decorative afterthought — it is the primary differentiator between utilitarian software and software that people fall in love with.

### The Physics of Tactility
Every digital element exists within a spatial continuum. By introducing subtle 3D perspective rotation (±6°) combined with cursor-aware dynamic lighting, users feel like they are directly manipulating tactile physical materials rather than passive pixels.

### Fluid Performance Over Heavy DOM
Achieving 60+ FPS while rendering complex particle fields, glassmorphism blurs, and animated borders requires strict GPU acceleration via CSS transform matrices, \`will-change\`, and isolated render contexts.`,
    coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    readTime: 6,
    claps: 2420,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    savedByMe: true,
    collection: 'Engineering & Design',
  },
  {
    id: 'art-2',
    authorId: 'user-marcus',
    title: 'From Static LLMs to Real-Time Spatial World Models',
    excerpt: 'A comprehensive survey on the transition from next-token autoregression to continuous 4D generative physical world simulations.',
    content: `The paradigm of AI is shifting rapidly from textual query-response cycles to real-time generative physics simulations. By predicting future latent states across spatial volumes, agents can plan multi-step manipulations in simulated physical environments before executing in the physical world.`,
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
    readTime: 10,
    claps: 4840,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    savedByMe: true,
    collection: 'Artificial Intelligence',
  },
  {
    id: 'art-3',
    authorId: 'user-elena',
    title: 'The Psychology of Ambient Sound Design in Virtual Spaces',
    excerpt: 'Exploring how psychoacoustic spatial audio and binaural micro-harmonics regulate focus and cognitive endurance during long creative sessions.',
    content: `Audio is the subconscious anchor of digital presence. When spatial cues accurately match visual horizon lines, the brain enters a flow state with significantly reduced cognitive friction.`,
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop',
    readTime: 5,
    claps: 1680,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    collection: 'Audio Architecture',
  },
  {
    id: 'art-4',
    authorId: 'user-valkyrie',
    title: 'Zero-Day Vulnerability Mitigation in Modern WebAssembly Engines',
    excerpt: 'An in-depth security analysis on side-channel memory leaks and speculative execution vulnerabilities in sandboxed WASM runtimes.',
    content: `As WebAssembly runtimes power edge functions and client-side high-performance applications, memory isolation guarantees must be validated against speculative execution side-channels. Here is how modern compilers implement dynamic canary boundaries.`,
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1200&auto=format&fit=crop',
    readTime: 8,
    claps: 2190,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    savedByMe: true,
    collection: 'Cybersecurity',
  }
];

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'vid-1',
    authorId: 'user-anya',
    title: 'Unreal Engine 5.4 Nanite & Volumetric Cloud Breakdown',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-city-with-flying-cars-41551-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    views: 28400,
    likes: 3150,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-2',
    authorId: 'user-chloe',
    title: 'Generative Particle Simulation in Three.js & GLSL Shaders',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-screens-41552-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=800&auto=format&fit=crop',
    views: 44200,
    likes: 6890,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    type: 'short',
  },
  {
    id: 'vid-3',
    authorId: 'user-jaxson',
    title: 'Custom Mech Keyboard CNC Milling & Sound Test Demo',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-typing-on-a-laptop-keyboard-41554-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop',
    views: 39800,
    likes: 4120,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    type: 'standard',
  },
  {
    id: 'vid-4',
    authorId: 'user-kai',
    title: 'Spatial WebXR 90 FPS Rendering on Standalone Headsets',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-futuristic-city-with-flying-cars-41551-large.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?q=80&w=800&auto=format&fit=crop',
    views: 21900,
    likes: 2480,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    type: 'short',
  }
];

export const MOCK_LIVESTREAMS: LiveStream[] = [
  {
    id: 'stream-1',
    hostId: 'user-elena',
    title: 'Live Modular Synth & Ambient Generative Sound Session 🎧',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    kind: 'audio',
    status: 'live',
    viewers: 642,
    startsAt: new Date().toISOString(),
    category: 'Music Production',
    guestIds: ['user-roy', 'user-kai'],
  },
  {
    id: 'stream-2',
    hostId: 'user-marcus',
    title: 'Building Realtime World Models live with PyTorch & WebGPU 🤖',
    coverUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'live',
    viewers: 1840,
    startsAt: new Date().toISOString(),
    category: 'AI Research',
    guestIds: ['user-maya'],
  },
  {
    id: 'stream-3',
    hostId: 'user-chloe',
    title: 'Creative Coding: Live Three.js Shader Architecture',
    coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'scheduled',
    viewers: 0,
    startsAt: new Date(Date.now() + 86400000).toISOString(),
    category: 'Digital Art',
    guestIds: [],
  },
  {
    id: 'stream-4',
    hostId: 'user-valkyrie',
    title: 'Live Binary Exploitation & CTF Reverse Engineering 🛡️',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    kind: 'video',
    status: 'live',
    viewers: 920,
    startsAt: new Date().toISOString(),
    category: 'Cybersecurity',
    guestIds: ['user-liam'],
  }
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-anya',
    participantIds: ['user-roy', 'user-anya'],
    lastMessage: {
      id: 'msg-1',
      conversationId: 'conv-anya',
      senderId: 'user-anya',
      content: 'Hey Ayush! Check out the volumetric fog lighting shaders I just pushed. Looking forward to your thoughts!',
      createdAt: new Date(Date.now() - 900000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'conv-aditi',
    participantIds: ['user-roy', 'user-aditi'],
    lastMessage: {
      id: 'msg-2',
      conversationId: 'conv-aditi',
      senderId: 'user-aditi',
      content: 'Hackathon landing page is ready for review! The theme selector and 3D banner look incredible.',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'conv-marcus',
    participantIds: ['user-roy', 'user-marcus'],
    lastMessage: {
      id: 'msg-3',
      conversationId: 'conv-marcus',
      senderId: 'user-marcus',
      content: 'Let’s sync tomorrow on the on-device WebGPU model inference pipeline.',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'conv-sophia',
    participantIds: ['user-roy', 'user-sophia'],
    lastMessage: {
      id: 'msg-4',
      conversationId: 'conv-sophia',
      senderId: 'user-sophia',
      content: 'The new collapsible sidebar and heart burst animations make the platform feel like a million bucks. 🔥',
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'conv-valkyrie',
    participantIds: ['user-roy', 'user-valkyrie'],
    lastMessage: {
      id: 'msg-5',
      conversationId: 'conv-valkyrie',
      senderId: 'user-valkyrie',
      content: 'Completed the security audit on our websocket connection tokens — all clean and encrypted!',
      createdAt: new Date(Date.now() - 259200000).toISOString(),
      read: true,
    },
    updatedAt: new Date(Date.now() - 259200000).toISOString(),
  }
];

export const MOCK_MESSAGES_BY_CONVERSATION: Record<string, Message[]> = {
  'conv-anya': [
    {
      id: 'msg-anya-1',
      conversationId: 'conv-anya',
      senderId: 'user-roy',
      content: 'Hey Anya, how is the biome rendering coming along?',
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      read: true,
    },
    {
      id: 'msg-anya-2',
      conversationId: 'conv-anya',
      senderId: 'user-anya',
      content: 'Just finished tuning Lumen and Nanite for the foliage assets! Looks super crisp.',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      read: true,
    },
    {
      id: 'msg-anya-3',
      conversationId: 'conv-anya',
      senderId: 'user-anya',
      content: 'Hey Ayush! Check out the volumetric fog lighting shaders I just pushed. Looking forward to your thoughts!',
      createdAt: new Date(Date.now() - 900000).toISOString(),
      read: true,
    }
  ],
  'conv-aditi': [
    {
      id: 'msg-aditi-1',
      conversationId: 'conv-aditi',
      senderId: 'user-roy',
      content: 'Let us finalize the $50k prize pool categories for the global hackathon today.',
      createdAt: new Date(Date.now() - 14400000).toISOString(),
      read: true,
    },
    {
      id: 'msg-aditi-2',
      conversationId: 'conv-aditi',
      senderId: 'user-aditi',
      content: 'Hackathon landing page is ready for review! The theme selector and 3D banner look incredible.',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      read: true,
    }
  ],
  'conv-marcus': [
    {
      id: 'msg-marcus-1',
      conversationId: 'conv-marcus',
      senderId: 'user-marcus',
      content: 'Let’s sync tomorrow on the on-device WebGPU model inference pipeline.',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      read: true,
    }
  ],
  'conv-sophia': [
    {
      id: 'msg-sophia-1',
      conversationId: 'conv-sophia',
      senderId: 'user-sophia',
      content: 'The new collapsible sidebar and heart burst animations make the platform feel like a million bucks. 🔥',
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      read: true,
    }
  ],
  'conv-valkyrie': [
    {
      id: 'msg-valk-1',
      conversationId: 'conv-valkyrie',
      senderId: 'user-roy',
      content: 'Hey Valkyrie, let us know once the token refresh audit is complete.',
      createdAt: new Date(Date.now() - 345600000).toISOString(),
      read: true,
    },
    {
      id: 'msg-valk-2',
      conversationId: 'conv-valkyrie',
      senderId: 'user-valkyrie',
      content: 'Completed the security audit on our websocket connection tokens — all clean and encrypted!',
      createdAt: new Date(Date.now() - 259200000).toISOString(),
      read: true,
    }
  ]
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'like',
    title: 'New Post Reaction',
    message: 'Anya Sharma, Sophia Chen, and 48 others liked your post "Designing for the Multiverse".',
    actorId: 'user-anya',
    targetId: 'post-1',
    read: false,
    createdAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'notif-2',
    type: 'follow',
    title: 'New Follower',
    message: 'Marcus Vance started following you.',
    actorId: 'user-marcus',
    targetId: 'user-roy',
    read: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'mention',
    title: 'Mentioned in Post',
    message: 'Aditi Singh mentioned you in "Multiverse Global Hackathon 2026".',
    actorId: 'user-aditi',
    targetId: 'post-6',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-4',
    type: 'comment',
    title: 'New Comment',
    message: 'Sophia Chen commented on your profile wall: "Love the ambient design!"',
    actorId: 'user-sophia',
    targetId: 'user-roy',
    read: true,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'notif-5',
    type: 'community',
    title: 'Community Trending',
    message: 'Spatial Computing & XR reached 12,000 members!',
    actorId: 'user-anya',
    targetId: 'comm-1',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'notif-6',
    type: 'event',
    title: 'Event Reminder',
    message: 'Midnight Synthwave & Ambient Live Session starts in 2 days.',
    actorId: 'user-elena',
    targetId: 'event-3',
    read: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  }
];
