// Generated by scripts/generate-api-contract.mjs. Do not edit manually.
export interface ApiRouteDefinition {
  method: "get" | "post" | "put" | "patch" | "delete";
  path: string;
  operationId: string;
  tag: string;
  summary: string;
  authenticated: boolean;
  roles: readonly string[];
}

export const apiRouteCatalog = [
  {
    "method": "get",
    "path": "/",
    "operationId": "getApiRoot",
    "tag": "system",
    "summary": "Get /",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "get",
    "path": "/achievements/me",
    "operationId": "getAchievementsMe",
    "tag": "achievements",
    "summary": "Get /achievements/me",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/ai/chat",
    "operationId": "postAiChat",
    "tag": "ai",
    "summary": "Post /ai/chat",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/ai/moderate",
    "operationId": "postAiModerate",
    "tag": "ai",
    "summary": "Post /ai/moderate",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/ai/search",
    "operationId": "getAiSearch",
    "tag": "ai",
    "summary": "Get /ai/search",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/articles",
    "operationId": "getArticles",
    "tag": "articles",
    "summary": "Get /articles",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/articles",
    "operationId": "postArticles",
    "tag": "articles",
    "summary": "Post /articles",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/articles/{id}",
    "operationId": "getArticlesById",
    "tag": "articles",
    "summary": "Get /articles/{id}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/articles/{id}",
    "operationId": "deleteArticlesById",
    "tag": "articles",
    "summary": "Delete /articles/{id}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/articles/{id}/clap",
    "operationId": "postArticlesByIdClap",
    "tag": "articles",
    "summary": "Post /articles/{id}/clap",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/auth/2fa/challenges",
    "operationId": "getAuth2faChallenges",
    "tag": "auth",
    "summary": "Get /auth/2fa/challenges",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/auth/2fa/challenges/{challengeId}",
    "operationId": "getAuth2faChallengesByChallengeId",
    "tag": "auth",
    "summary": "Get /auth/2fa/challenges/{challengeId}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/2fa/challenges/{challengeId}/approve",
    "operationId": "postAuth2faChallengesByChallengeIdApprove",
    "tag": "auth",
    "summary": "Post /auth/2fa/challenges/{challengeId}/approve",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/2fa/challenges/{challengeId}/complete",
    "operationId": "postAuth2faChallengesByChallengeIdComplete",
    "tag": "auth",
    "summary": "Post /auth/2fa/challenges/{challengeId}/complete",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/2fa/challenges/{challengeId}/deny",
    "operationId": "postAuth2faChallengesByChallengeIdDeny",
    "tag": "auth",
    "summary": "Post /auth/2fa/challenges/{challengeId}/deny",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/2fa/confirm",
    "operationId": "postAuth2faConfirm",
    "tag": "auth",
    "summary": "Post /auth/2fa/confirm",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/2fa/disable",
    "operationId": "postAuth2faDisable",
    "tag": "auth",
    "summary": "Post /auth/2fa/disable",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/2fa/setup",
    "operationId": "postAuth2faSetup",
    "tag": "auth",
    "summary": "Post /auth/2fa/setup",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/email-otp/send",
    "operationId": "postAuthEmailOtpSend",
    "tag": "auth",
    "summary": "Post /auth/email-otp/send",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/email-otp/verify",
    "operationId": "postAuthEmailOtpVerify",
    "tag": "auth",
    "summary": "Post /auth/email-otp/verify",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/google",
    "operationId": "postAuthGoogle",
    "tag": "auth",
    "summary": "Post /auth/google",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/login",
    "operationId": "postAuthLogin",
    "tag": "auth",
    "summary": "Post /auth/login",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/logout",
    "operationId": "postAuthLogout",
    "tag": "auth",
    "summary": "Post /auth/logout",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/logout-all",
    "operationId": "postAuthLogoutAll",
    "tag": "auth",
    "summary": "Post /auth/logout-all",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/otp/send",
    "operationId": "postAuthOtpSend",
    "tag": "auth",
    "summary": "Post /auth/otp/send",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/otp/verify",
    "operationId": "postAuthOtpVerify",
    "tag": "auth",
    "summary": "Post /auth/otp/verify",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/refresh",
    "operationId": "postAuthRefresh",
    "tag": "auth",
    "summary": "Post /auth/refresh",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/register",
    "operationId": "postAuthRegister",
    "tag": "auth",
    "summary": "Post /auth/register",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/reset-password",
    "operationId": "postAuthResetPassword",
    "tag": "auth",
    "summary": "Post /auth/reset-password",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/reset-password/confirm",
    "operationId": "postAuthResetPasswordConfirm",
    "tag": "auth",
    "summary": "Post /auth/reset-password/confirm",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "get",
    "path": "/auth/verify-email/{token}",
    "operationId": "getAuthVerifyEmailByToken",
    "tag": "auth",
    "summary": "Get /auth/verify-email/{token}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/verify-email/resend",
    "operationId": "postAuthVerifyEmailResend",
    "tag": "auth",
    "summary": "Post /auth/verify-email/resend",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/auth/verify-email/resend-public",
    "operationId": "postAuthVerifyEmailResendPublic",
    "tag": "auth",
    "summary": "Post /auth/verify-email/resend-public",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "get",
    "path": "/broadcast-channels",
    "operationId": "getBroadcastChannels",
    "tag": "broadcast-channels",
    "summary": "Get /broadcast-channels",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/broadcast-channels",
    "operationId": "postBroadcastChannels",
    "tag": "broadcast-channels",
    "summary": "Post /broadcast-channels",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/broadcast-channels/{id}/join",
    "operationId": "postBroadcastChannelsByIdJoin",
    "tag": "broadcast-channels",
    "summary": "Post /broadcast-channels/{id}/join",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/broadcast-channels/{id}/join",
    "operationId": "deleteBroadcastChannelsByIdJoin",
    "tag": "broadcast-channels",
    "summary": "Delete /broadcast-channels/{id}/join",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/broadcast-channels/{id}/messages",
    "operationId": "getBroadcastChannelsByIdMessages",
    "tag": "broadcast-channels",
    "summary": "Get /broadcast-channels/{id}/messages",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/broadcast-channels/{id}/messages",
    "operationId": "postBroadcastChannelsByIdMessages",
    "tag": "broadcast-channels",
    "summary": "Post /broadcast-channels/{id}/messages",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/broadcast-channels/{id}/messages/{messageId}/react",
    "operationId": "postBroadcastChannelsByIdMessagesByMessageIdReact",
    "tag": "broadcast-channels",
    "summary": "Post /broadcast-channels/{id}/messages/{messageId}/react",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "patch",
    "path": "/broadcast-channels/{id}/notifications",
    "operationId": "patchBroadcastChannelsByIdNotifications",
    "tag": "broadcast-channels",
    "summary": "Patch /broadcast-channels/{id}/notifications",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/business",
    "operationId": "getBusiness",
    "tag": "business",
    "summary": "Get /business",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/business",
    "operationId": "postBusiness",
    "tag": "business",
    "summary": "Post /business",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/communities",
    "operationId": "getCommunities",
    "tag": "communities",
    "summary": "Get /communities",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/communities",
    "operationId": "postCommunities",
    "tag": "communities",
    "summary": "Post /communities",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/communities/{id}",
    "operationId": "getCommunitiesById",
    "tag": "communities",
    "summary": "Get /communities/{id}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "get",
    "path": "/communities/{id}/discussions",
    "operationId": "getCommunitiesByIdDiscussions",
    "tag": "communities",
    "summary": "Get /communities/{id}/discussions",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/communities/{id}/discussions",
    "operationId": "postCommunitiesByIdDiscussions",
    "tag": "communities",
    "summary": "Post /communities/{id}/discussions",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/communities/{id}/discussions/{discussionId}/like",
    "operationId": "postCommunitiesByIdDiscussionsByDiscussionIdLike",
    "tag": "communities",
    "summary": "Post /communities/{id}/discussions/{discussionId}/like",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/communities/{id}/join",
    "operationId": "postCommunitiesByIdJoin",
    "tag": "communities",
    "summary": "Post /communities/{id}/join",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/communities/{id}/leave",
    "operationId": "postCommunitiesByIdLeave",
    "tag": "communities",
    "summary": "Post /communities/{id}/leave",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/conversations",
    "operationId": "getConversations",
    "tag": "conversations",
    "summary": "Get /conversations",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/conversations/{conversationId}/messages",
    "operationId": "getConversationsByConversationIdMessages",
    "tag": "conversations",
    "summary": "Get /conversations/{conversationId}/messages",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "put",
    "path": "/conversations/{conversationId}/vanish",
    "operationId": "putConversationsByConversationIdVanish",
    "tag": "conversations",
    "summary": "Put /conversations/{conversationId}/vanish",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/conversations/group",
    "operationId": "postConversationsGroup",
    "tag": "conversations",
    "summary": "Post /conversations/group",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/creator/workspace",
    "operationId": "getCreatorWorkspace",
    "tag": "creator",
    "summary": "Get /creator/workspace",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "put",
    "path": "/creator/workspace",
    "operationId": "putCreatorWorkspace",
    "tag": "creator",
    "summary": "Put /creator/workspace",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/creator/workspace/{kind}/{itemKey}",
    "operationId": "deleteCreatorWorkspaceByKindByItemKey",
    "tag": "creator",
    "summary": "Delete /creator/workspace/{kind}/{itemKey}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/docs",
    "operationId": "getDocs",
    "tag": "docs",
    "summary": "Get /docs",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "get",
    "path": "/economy/analytics",
    "operationId": "getEconomyAnalytics",
    "tag": "economy",
    "summary": "Get /economy/analytics",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/economy/orders",
    "operationId": "postEconomyOrders",
    "tag": "economy",
    "summary": "Post /economy/orders",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/economy/orders/{orderId}/verify",
    "operationId": "postEconomyOrdersByOrderIdVerify",
    "tag": "economy",
    "summary": "Post /economy/orders/{orderId}/verify",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/economy/superchat",
    "operationId": "postEconomySuperchat",
    "tag": "economy",
    "summary": "Post /economy/superchat",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/economy/wallet",
    "operationId": "getEconomyWallet",
    "tag": "economy",
    "summary": "Get /economy/wallet",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/events",
    "operationId": "getEvents",
    "tag": "events",
    "summary": "Get /events",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/events",
    "operationId": "postEvents",
    "tag": "events",
    "summary": "Post /events",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/events/{id}",
    "operationId": "getEventsById",
    "tag": "events",
    "summary": "Get /events/{id}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/events/{id}",
    "operationId": "deleteEventsById",
    "tag": "events",
    "summary": "Delete /events/{id}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/events/{id}/rsvp",
    "operationId": "postEventsByIdRsvp",
    "tag": "events",
    "summary": "Post /events/{id}/rsvp",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/feed",
    "operationId": "getFeed",
    "tag": "feed",
    "summary": "Get /feed",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/feed/trending",
    "operationId": "getFeedTrending",
    "tag": "feed",
    "summary": "Get /feed/trending",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/healthz",
    "operationId": "getHealthz",
    "tag": "healthz",
    "summary": "Get /healthz",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/invites/claim",
    "operationId": "postInvitesClaim",
    "tag": "invites",
    "summary": "Post /invites/claim",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/invites/generate",
    "operationId": "postInvitesGenerate",
    "tag": "invites",
    "summary": "Post /invites/generate",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/livez",
    "operationId": "getLivez",
    "tag": "livez",
    "summary": "Get /livez",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "get",
    "path": "/media/{id}/hls",
    "operationId": "getMediaByIdHls",
    "tag": "media",
    "summary": "Get /media/{id}/hls",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/media/presign",
    "operationId": "postMediaPresign",
    "tag": "media",
    "summary": "Post /media/presign",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/media/upload",
    "operationId": "postMediaUpload",
    "tag": "media",
    "summary": "Post /media/upload",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/messages",
    "operationId": "postMessages",
    "tag": "messages",
    "summary": "Post /messages",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "put",
    "path": "/messages/{messageId}",
    "operationId": "putMessagesByMessageId",
    "tag": "messages",
    "summary": "Put /messages/{messageId}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/messages/{messageId}",
    "operationId": "deleteMessagesByMessageId",
    "tag": "messages",
    "summary": "Delete /messages/{messageId}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/messages/{messageId}/pin",
    "operationId": "postMessagesByMessageIdPin",
    "tag": "messages",
    "summary": "Post /messages/{messageId}/pin",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/messages/{messageId}/reactions",
    "operationId": "postMessagesByMessageIdReactions",
    "tag": "messages",
    "summary": "Post /messages/{messageId}/reactions",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/messages/{messageId}/seen",
    "operationId": "postMessagesByMessageIdSeen",
    "tag": "messages",
    "summary": "Post /messages/{messageId}/seen",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/notes",
    "operationId": "getNotes",
    "tag": "notes",
    "summary": "Get /notes",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/notes",
    "operationId": "postNotes",
    "tag": "notes",
    "summary": "Post /notes",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/notes/{id}",
    "operationId": "deleteNotesById",
    "tag": "notes",
    "summary": "Delete /notes/{id}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/notifications",
    "operationId": "getNotifications",
    "tag": "notifications",
    "summary": "Get /notifications",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/notifications/{notificationId}/read",
    "operationId": "postNotificationsByNotificationIdRead",
    "tag": "notifications",
    "summary": "Post /notifications/{notificationId}/read",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/notifications/push/public-key",
    "operationId": "getNotificationsPushPublicKey",
    "tag": "notifications",
    "summary": "Get /notifications/push/public-key",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/notifications/push/subscribe",
    "operationId": "postNotificationsPushSubscribe",
    "tag": "notifications",
    "summary": "Post /notifications/push/subscribe",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/notifications/push/subscribe",
    "operationId": "deleteNotificationsPushSubscribe",
    "tag": "notifications",
    "summary": "Delete /notifications/push/subscribe",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/notifications/read-all",
    "operationId": "postNotificationsReadAll",
    "tag": "notifications",
    "summary": "Post /notifications/read-all",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/onboarding/complete",
    "operationId": "postOnboardingComplete",
    "tag": "onboarding",
    "summary": "Post /onboarding/complete",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts",
    "operationId": "postPosts",
    "tag": "posts",
    "summary": "Post /posts",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/posts/{postId}",
    "operationId": "getPostsByPostId",
    "tag": "posts",
    "summary": "Get /posts/{postId}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "put",
    "path": "/posts/{postId}",
    "operationId": "putPostsByPostId",
    "tag": "posts",
    "summary": "Put /posts/{postId}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/posts/{postId}",
    "operationId": "deletePostsByPostId",
    "tag": "posts",
    "summary": "Delete /posts/{postId}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/{postId}/bookmark",
    "operationId": "postPostsByPostIdBookmark",
    "tag": "posts",
    "summary": "Post /posts/{postId}/bookmark",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/posts/{postId}/comments",
    "operationId": "getPostsByPostIdComments",
    "tag": "posts",
    "summary": "Get /posts/{postId}/comments",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/{postId}/comments",
    "operationId": "postPostsByPostIdComments",
    "tag": "posts",
    "summary": "Post /posts/{postId}/comments",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/{postId}/comments/{commentId}/like",
    "operationId": "postPostsByPostIdCommentsByCommentIdLike",
    "tag": "posts",
    "summary": "Post /posts/{postId}/comments/{commentId}/like",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/{postId}/comments/{commentId}/replies",
    "operationId": "postPostsByPostIdCommentsByCommentIdReplies",
    "tag": "posts",
    "summary": "Post /posts/{postId}/comments/{commentId}/replies",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/{postId}/like",
    "operationId": "postPostsByPostIdLike",
    "tag": "posts",
    "summary": "Post /posts/{postId}/like",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/{postId}/poll/vote",
    "operationId": "postPostsByPostIdPollVote",
    "tag": "posts",
    "summary": "Post /posts/{postId}/poll/vote",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/{postId}/repost",
    "operationId": "postPostsByPostIdRepost",
    "tag": "posts",
    "summary": "Post /posts/{postId}/repost",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/posts/{postId}/repost",
    "operationId": "deletePostsByPostIdRepost",
    "tag": "posts",
    "summary": "Delete /posts/{postId}/repost",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/{postId}/share",
    "operationId": "postPostsByPostIdShare",
    "tag": "posts",
    "summary": "Post /posts/{postId}/share",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/{postId}/unlike",
    "operationId": "postPostsByPostIdUnlike",
    "tag": "posts",
    "summary": "Post /posts/{postId}/unlike",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/posts/liked",
    "operationId": "getPostsLiked",
    "tag": "posts",
    "summary": "Get /posts/liked",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/posts/saved",
    "operationId": "getPostsSaved",
    "tag": "posts",
    "summary": "Get /posts/saved",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/posts/upload-image",
    "operationId": "postPostsUploadImage",
    "tag": "posts",
    "summary": "Post /posts/upload-image",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/products",
    "operationId": "getProducts",
    "tag": "products",
    "summary": "Get /products",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/products",
    "operationId": "postProducts",
    "tag": "products",
    "summary": "Post /products",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/products/{id}",
    "operationId": "getProductsById",
    "tag": "products",
    "summary": "Get /products/{id}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/products/{id}",
    "operationId": "deleteProductsById",
    "tag": "products",
    "summary": "Delete /products/{id}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/products/{id}/order",
    "operationId": "postProductsByIdOrder",
    "tag": "products",
    "summary": "Post /products/{id}/order",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/products/{id}/save",
    "operationId": "postProductsByIdSave",
    "tag": "products",
    "summary": "Post /products/{id}/save",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/products/orders",
    "operationId": "getProductsOrders",
    "tag": "products",
    "summary": "Get /products/orders",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/products/orders/{orderId}/cancel",
    "operationId": "postProductsOrdersByOrderIdCancel",
    "tag": "products",
    "summary": "Post /products/orders/{orderId}/cancel",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/products/orders/{orderId}/fulfill",
    "operationId": "postProductsOrdersByOrderIdFulfill",
    "tag": "products",
    "summary": "Post /products/orders/{orderId}/fulfill",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/products/orders/{orderId}/verify",
    "operationId": "postProductsOrdersByOrderIdVerify",
    "tag": "products",
    "summary": "Post /products/orders/{orderId}/verify",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/projects",
    "operationId": "getProjects",
    "tag": "projects",
    "summary": "Get /projects",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/projects",
    "operationId": "postProjects",
    "tag": "projects",
    "summary": "Post /projects",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/projects/{projectId}/collaborators",
    "operationId": "postProjectsByProjectIdCollaborators",
    "tag": "projects",
    "summary": "Post /projects/{projectId}/collaborators",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/projects/{projectId}/collaborators/respond",
    "operationId": "postProjectsByProjectIdCollaboratorsRespond",
    "tag": "projects",
    "summary": "Post /projects/{projectId}/collaborators/respond",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/projects/invitations",
    "operationId": "getProjectsInvitations",
    "tag": "projects",
    "summary": "Get /projects/invitations",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/readyz",
    "operationId": "getReadyz",
    "tag": "readyz",
    "summary": "Get /readyz",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/reports",
    "operationId": "postReports",
    "tag": "reports",
    "summary": "Post /reports",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "patch",
    "path": "/reports/{reportId}/status",
    "operationId": "patchReportsByReportIdStatus",
    "tag": "reports",
    "summary": "Patch /reports/{reportId}/status",
    "authenticated": true,
    "roles": [
      "admin",
      "moderator"
    ]
  },
  {
    "method": "post",
    "path": "/reports/grievance",
    "operationId": "postReportsGrievance",
    "tag": "reports",
    "summary": "Post /reports/grievance",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "get",
    "path": "/reports/grievance/{ticketId}",
    "operationId": "getReportsGrievanceByTicketId",
    "tag": "reports",
    "summary": "Get /reports/grievance/{ticketId}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "get",
    "path": "/reports/queue",
    "operationId": "getReportsQueue",
    "tag": "reports",
    "summary": "Get /reports/queue",
    "authenticated": true,
    "roles": [
      "admin",
      "moderator"
    ]
  },
  {
    "method": "get",
    "path": "/search",
    "operationId": "getSearch",
    "tag": "search",
    "summary": "Get /search",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/stories",
    "operationId": "getStories",
    "tag": "stories",
    "summary": "Get /stories",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/stories",
    "operationId": "postStories",
    "tag": "stories",
    "summary": "Post /stories",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/stories/{id}/poll/vote",
    "operationId": "postStoriesByIdPollVote",
    "tag": "stories",
    "summary": "Post /stories/{id}/poll/vote",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/stories/{id}/react",
    "operationId": "postStoriesByIdReact",
    "tag": "stories",
    "summary": "Post /stories/{id}/react",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/stories/{id}/view",
    "operationId": "postStoriesByIdView",
    "tag": "stories",
    "summary": "Post /stories/{id}/view",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/streams",
    "operationId": "getStreams",
    "tag": "streams",
    "summary": "Get /streams",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/streams",
    "operationId": "postStreams",
    "tag": "streams",
    "summary": "Post /streams",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/streams/{id}",
    "operationId": "getStreamsById",
    "tag": "streams",
    "summary": "Get /streams/{id}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "put",
    "path": "/streams/{id}/status",
    "operationId": "putStreamsByIdStatus",
    "tag": "streams",
    "summary": "Put /streams/{id}/status",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/streams/{id}/token",
    "operationId": "getStreamsByIdToken",
    "tag": "streams",
    "summary": "Get /streams/{id}/token",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/subscriptions/{id}",
    "operationId": "deleteSubscriptionsById",
    "tag": "subscriptions",
    "summary": "Delete /subscriptions/{id}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/subscriptions/{id}/verify",
    "operationId": "postSubscriptionsByIdVerify",
    "tag": "subscriptions",
    "summary": "Post /subscriptions/{id}/verify",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/subscriptions/my-subscriptions",
    "operationId": "getSubscriptionsMySubscriptions",
    "tag": "subscriptions",
    "summary": "Get /subscriptions/my-subscriptions",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/subscriptions/subscribe",
    "operationId": "postSubscriptionsSubscribe",
    "tag": "subscriptions",
    "summary": "Post /subscriptions/subscribe",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/subscriptions/tiers/{creatorId}",
    "operationId": "getSubscriptionsTiersByCreatorId",
    "tag": "subscriptions",
    "summary": "Get /subscriptions/tiers/{creatorId}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/{userId}",
    "operationId": "getUsersByUserId",
    "tag": "users",
    "summary": "Get /users/{userId}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/block",
    "operationId": "postUsersByUserIdBlock",
    "tag": "users",
    "summary": "Post /users/{userId}/block",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/close-friend",
    "operationId": "postUsersByUserIdCloseFriend",
    "tag": "users",
    "summary": "Post /users/{userId}/close-friend",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/users/{userId}/close-friend",
    "operationId": "deleteUsersByUserIdCloseFriend",
    "tag": "users",
    "summary": "Delete /users/{userId}/close-friend",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/favorite",
    "operationId": "postUsersByUserIdFavorite",
    "tag": "users",
    "summary": "Post /users/{userId}/favorite",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/users/{userId}/favorite",
    "operationId": "deleteUsersByUserIdFavorite",
    "tag": "users",
    "summary": "Delete /users/{userId}/favorite",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/{userId}/feed",
    "operationId": "getUsersByUserIdFeed",
    "tag": "users",
    "summary": "Get /users/{userId}/feed",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/follow",
    "operationId": "postUsersByUserIdFollow",
    "tag": "users",
    "summary": "Post /users/{userId}/follow",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/{userId}/followers",
    "operationId": "getUsersByUserIdFollowers",
    "tag": "users",
    "summary": "Get /users/{userId}/followers",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/{userId}/following",
    "operationId": "getUsersByUserIdFollowing",
    "tag": "users",
    "summary": "Get /users/{userId}/following",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/mute",
    "operationId": "postUsersByUserIdMute",
    "tag": "users",
    "summary": "Post /users/{userId}/mute",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/{userId}/profile-comments",
    "operationId": "getUsersByUserIdProfileComments",
    "tag": "users",
    "summary": "Get /users/{userId}/profile-comments",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/profile-comments",
    "operationId": "postUsersByUserIdProfileComments",
    "tag": "users",
    "summary": "Post /users/{userId}/profile-comments",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/users/{userId}/profile-comments/{commentId}",
    "operationId": "deleteUsersByUserIdProfileCommentsByCommentId",
    "tag": "users",
    "summary": "Delete /users/{userId}/profile-comments/{commentId}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/{userId}/showcases",
    "operationId": "getUsersByUserIdShowcases",
    "tag": "users",
    "summary": "Get /users/{userId}/showcases",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/showcases",
    "operationId": "postUsersByUserIdShowcases",
    "tag": "users",
    "summary": "Post /users/{userId}/showcases",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/users/{userId}/showcases/{showcaseId}",
    "operationId": "deleteUsersByUserIdShowcasesByShowcaseId",
    "tag": "users",
    "summary": "Delete /users/{userId}/showcases/{showcaseId}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/unblock",
    "operationId": "postUsersByUserIdUnblock",
    "tag": "users",
    "summary": "Post /users/{userId}/unblock",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/unfollow",
    "operationId": "postUsersByUserIdUnfollow",
    "tag": "users",
    "summary": "Post /users/{userId}/unfollow",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/{userId}/unmute",
    "operationId": "postUsersByUserIdUnmute",
    "tag": "users",
    "summary": "Post /users/{userId}/unmute",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/by-username/{username}",
    "operationId": "getUsersByUsernameByUsername",
    "tag": "users",
    "summary": "Get /users/by-username/{username}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/me",
    "operationId": "getUsersMe",
    "tag": "users",
    "summary": "Get /users/me",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "put",
    "path": "/users/me",
    "operationId": "putUsersMe",
    "tag": "users",
    "summary": "Put /users/me",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/users/me",
    "operationId": "deleteUsersMe",
    "tag": "users",
    "summary": "Delete /users/me",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/me/avatar",
    "operationId": "postUsersMeAvatar",
    "tag": "users",
    "summary": "Post /users/me/avatar",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/me/close-friends",
    "operationId": "getUsersMeCloseFriends",
    "tag": "users",
    "summary": "Get /users/me/close-friends",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/me/contact-shields",
    "operationId": "getUsersMeContactShields",
    "tag": "users",
    "summary": "Get /users/me/contact-shields",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/me/contact-shields",
    "operationId": "postUsersMeContactShields",
    "tag": "users",
    "summary": "Post /users/me/contact-shields",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/users/me/contact-shields/{shieldId}",
    "operationId": "deleteUsersMeContactShieldsByShieldId",
    "tag": "users",
    "summary": "Delete /users/me/contact-shields/{shieldId}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/me/export",
    "operationId": "getUsersMeExport",
    "tag": "users",
    "summary": "Get /users/me/export",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/me/favorites/creators",
    "operationId": "getUsersMeFavoritesCreators",
    "tag": "users",
    "summary": "Get /users/me/favorites/creators",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/me/follow-requests",
    "operationId": "getUsersMeFollowRequests",
    "tag": "users",
    "summary": "Get /users/me/follow-requests",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/me/follow-requests/{requestId}/accept",
    "operationId": "postUsersMeFollowRequestsByRequestIdAccept",
    "tag": "users",
    "summary": "Post /users/me/follow-requests/{requestId}/accept",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/users/me/follow-requests/{requestId}/reject",
    "operationId": "postUsersMeFollowRequestsByRequestIdReject",
    "tag": "users",
    "summary": "Post /users/me/follow-requests/{requestId}/reject",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "put",
    "path": "/users/me/privacy",
    "operationId": "putUsersMePrivacy",
    "tag": "users",
    "summary": "Put /users/me/privacy",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "put",
    "path": "/users/me/settings",
    "operationId": "putUsersMeSettings",
    "tag": "users",
    "summary": "Put /users/me/settings",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/users/search",
    "operationId": "getUsersSearch",
    "tag": "users",
    "summary": "Get /users/search",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/videos",
    "operationId": "getVideos",
    "tag": "videos",
    "summary": "Get /videos",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "post",
    "path": "/videos",
    "operationId": "postVideos",
    "tag": "videos",
    "summary": "Post /videos",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/videos/{id}",
    "operationId": "getVideosById",
    "tag": "videos",
    "summary": "Get /videos/{id}",
    "authenticated": false,
    "roles": []
  },
  {
    "method": "delete",
    "path": "/videos/{id}",
    "operationId": "deleteVideosById",
    "tag": "videos",
    "summary": "Delete /videos/{id}",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/videos/{id}/bookmark",
    "operationId": "postVideosByIdBookmark",
    "tag": "videos",
    "summary": "Post /videos/{id}/bookmark",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/videos/{id}/comments",
    "operationId": "getVideosByIdComments",
    "tag": "videos",
    "summary": "Get /videos/{id}/comments",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/videos/{id}/comments",
    "operationId": "postVideosByIdComments",
    "tag": "videos",
    "summary": "Post /videos/{id}/comments",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/videos/{id}/comments/{commentId}/like",
    "operationId": "postVideosByIdCommentsByCommentIdLike",
    "tag": "videos",
    "summary": "Post /videos/{id}/comments/{commentId}/like",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "post",
    "path": "/videos/{id}/like",
    "operationId": "postVideosByIdLike",
    "tag": "videos",
    "summary": "Post /videos/{id}/like",
    "authenticated": true,
    "roles": []
  },
  {
    "method": "get",
    "path": "/videos/saved",
    "operationId": "getVideosSaved",
    "tag": "videos",
    "summary": "Get /videos/saved",
    "authenticated": true,
    "roles": []
  }
] as const satisfies readonly ApiRouteDefinition[];
